### ISSUE TITLE
Failed to download resource "pkg-config"

### ISSUE THREAD

**Issue by nbargues** [tseemann/nullarbor#102]
Hi,
I try to install nullarbor and I have some problem; when I arrive to "brew install nullarbor --HEAD", i have the message: 

bargues@bargues-Precision-Tower-5810:~$ brew install nullarbor --HEAD
==> Auto-updated Homebrew!
Updated Homebrew from 92bb61c to a4416e2.
No changes to formulae.

==> Installing nullarbor from tseemann/bioinformatics-linux
==> Installing dependencies for tseemann/bioinformatics-linux/nullarbor: pkg-config, linuxbrew/xorg/util-macros, linuxbrew/xorg/xextproto, linuxbrew/xorg/bigreqsproto, linuxbrew/xorg/compositeproto, linuxbrew/xorg/damageproto, linuxbrew/xorg/dmxproto, linuxbrew/xorg/dri2proto, linuxbrew/xorg/dri3proto, linuxbrew/xorg/fixesproto, linuxbrew/xorg/fontsproto, linuxbrew/xorg/glproto, linuxbrew/xorg/inputproto, linuxbrew/xorg/kbproto, linuxbrew/xorg/presentproto, linuxbrew/xorg/randrproto, linuxbrew/xorg/recordproto, linuxbrew/xorg/renderproto, linuxbrew/xorg/resourceproto, linuxbrew/xorg/scrnsaverproto, linuxbrew/xorg/videoproto, linuxbrew/xorg/xcmiscproto, linuxbrew/xorg/xf86bigfontproto, linuxbrew/xorg/xf86dgaproto, linuxbrew/xorg/xf86driproto, linuxbrew/xorg/xf86vidmodeproto, linuxbrew/xorg/xineramaproto, linuxbrew/xorg/xproto, linuxbrew/xorg/xorg-protocols, linuxbrew/xorg/libxau, linuxbrew/xorg/xcb-proto, linuxbrew/xorg/libpthread-stubs, linuxbrew/xorg/libxdmcp, gmp, mpfr, ncurses, readline, gawk, check, linuxbrew/xorg/libxcb, linuxbrew/xorg/libx11, linuxbrew/xorg/libxext, linuxbrew/xorg/libfs, linuxbrew/xorg/libice, linuxbrew/xorg/libsm, linuxbrew/xorg/libxscrnsaver, linuxbrew/xorg/libxt, linuxbrew/xorg/libxmu, libxml2, gettext, linuxbrew/xorg/libxpm, linuxbrew/xorg/libxaw, linuxbrew/xorg/libxfixes, linuxbrew/xorg/libxcomposite, linuxbrew/xorg/libxrender, linuxbrew/xorg/libxcursor, linuxbrew/xorg/libxdamage, linuxbrew/xorg/font-util, linuxbrew/xorg/libfontenc, freetype, linuxbrew/xorg/libxfont, expat, fontconfig, linuxbrew/xorg/libxft, linuxbrew/xorg/libxi, linuxbrew/xorg/libxinerama, linuxbrew/xorg/libxrandr, linuxbrew/xorg/libxres, linuxbrew/xorg/libxtst, linuxbrew/xorg/libxv, linuxbrew/xorg/libxvmc, linuxbrew/xorg/libxxf86dga, linuxbrew/xorg/libxxf86vm, linuxbrew/xorg/libdmx, linuxbrew/xorg/libpciaccess, linuxbrew/xorg/libxkbfile, linuxbrew/xorg/libxshmfence, linuxbrew/xorg/xorg, sqlite, gdbm, berkeley-db@4, python, blast, infernal, hmmer, aragorn, prodigal, tbl2asn, minced, barrnap, prokka, fasttree, megahit, libmpc, isl, gcc, spades, kraken, trimmomatic, mlst, abricate, newick-utils, capnp, gsl, mash, libtool, libtiff, pixman, m4, autoconf, automake, libffi, util-linux, glib, cairo, bison, help2man, flex, gobject-introspection, shared-mime-info, gdk-pixbuf, libcroco, icu4c, harfbuzz, pango, librsvg, imagemagick, bwa, samtools, tseemann/bioinformatics-linux/snippy, bedtools, cd-hit, mcl, mafft, exonerate, prank, tseemann/bioinformatics-linux/roary
==> Installing tseemann/bioinformatics-linux/nullarbor dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz

curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Trying a mirror...
==> Downloading https://fossies.org/linux/misc/pkg-config-0.29.2.tar.gz

curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "pkg-config"
Download failed: https://fossies.org/linux/misc/pkg-config-0.29.2.tar.gz

Any idea how to fix the problem ?

Best regards, Nicolas

**Comment by tseemann** [comment]
Nicolas
You have a problem with your Linuxbrew setup.  What does `brew doctor` say?
