### ISSUE TITLE
Assembly quality interpretation

### ISSUE THREAD

**Issue by alantsangmb** [tseemann/nullarbor#105]
Hi, I read from the Report.pm that the quality of an assembly would be indicated as fail if the no. of contigs exceed 1000, or the no. of CDS >> #kbp

However, the following is one of my isolate assembly result and I can't understand why the quality is indicated as fail:

Contigs 	bp 	ok 	Ns 	gaps 	min 	avg 	max 	N50 	Insert size (25,50,75)% 	CDS 	rRNA 	tRNA 	tmRNA 	Quality 
106	5198877	5198581	296	0	128	49046	907847	282875	(282, 374, 477) 	4908	10	88	1	✘

**Comment by tseemann** [comment]
The quality traffic lights are just a "guide" - they are not "truth".

If your statistics are an outlier compared to the other isolates in the set you ran, it will  show it as failed.  Usually we expect the isolates to be quite similar. I guess the other assemblies were different in size or number of contigs?

**Comment by alantsangmb** [comment]
Thanks Torsten! Yes exactly! That isolate is different from others (that is another serotype/group from others):

Isolate	Contigs 	bp 	ok 	Ns 	gaps 	min 	avg 	max 	N50 	Insert size (25,50,75)% 	CDS 	rRNA 	tRNA 	tmRNA 	Quality 
A 	33 	4703981 	4703787 	194 	0 	128 	142544 	1549838 	490295 	(413, 524, 656) 	4412 	9 	81 	1 	✔ 
B 	31 	4703655 	4703459 	196 	0 	128 	151730 	1549838 	490295 	(391, 502, 634) 	4412 	9 	80 	1 	✔ 
C 	30 	4712626 	4712431 	195 	0 	128 	157087 	1549911 	490295 	(399, 499, 619) 	4419 	9 	80 	1 	✔ 
D 	106 	5198877 	5198581 	296 	0 	128 	49046 	907847 	282875 	(282, 374, 477) 	4908 	10 	88 	1 	✘ 

Thank you for your explanation. I am closing this issue.

**Comment by tseemann** [comment]
Great - glad it makes sense now.   You question was a fair one - the traffic light system is immature still. It aims for sensitivity rather than specifity.  I just want to alert the human, so they can quickly make a good judgement.

FYI you can click on the Quality column header and it will sort them so you can see all the bad fail ones together.
