### ISSUE TITLE
SNPs number reported by snippy

### ISSUE THREAD

**Issue by alantsangmb** [tseemann/nullarbor#107]
Hello, Torsten

I am analyzing some data from Miseq using nullabor with default values.
When I look into the SNPs results, I found that the base occurrence shown in the Evidence column is different from the actual number of reads mapped in the bam file.

For example, there are 13 'G' in a particular position reported in the snp.html.
When I looked into the bam file using Artemis,  there are total 16 reads and 16 'G' in that particular position.

Similar observation was seen in another adjacent position that no SNP is called in that position, but the absolute count from the bam file is 11 reads and all are 'G' against the reference 'A'.  Do you know what makes the counting reduce?  Is it related to the base quality or mapqual?  I don't want to adjust the mincov default cutoff of 10. What other parameters can I adjust to accept the lower quality base?

Thank you so much!

**Comment by tseemann** [comment]
I only use reads with mapping quality Q60 or higher (from `--mapqual`) and I only include bases of quality Q20 or higher (< 0.01 error rate).  

My guess they are low quality bases, so they appear in a alignment viewer but didn't count in Snippy.

**Comment by alantsangmb** [comment]
Your guess is right!
I have checked the quality of that base is lower than Q20 from 2 reads out of the 11 reads, resulting the coverage of 9 and hence no variant was called. Thank you so much!

**Comment by tseemann** [comment]
@alantsangmb thank you for reporting this - i need to add this to the documentation. I am impressed by your good detective work!
