### ISSUE TITLE
Error 127 - help

### ISSUE THREAD

**Issue by motroy** [tseemann/nullarbor#111]
Hi Prof. Seemann,
Thank you for the excellent pipeline (and other tools). I have successfully run nullarbor with 4 samples, now tried 16 samples and when it reached the FastTree step, received the following:
....
FastTree Version 2.1.10 SSE3
Alignment: core.aln
Nucleotide distances: Jukes-Cantor Joins: balanced Support: SH-like 1000
Search: Normal +NNI +SPR (2 rounds range 10) +ML-NNI opt-each=1
TopHits: 1.00*sqrtN close=default refresh=0.80
ML Model: Generalized Time-Reversible, CAT approximation with 20 rate categories
nw_order: error while loading shared libraries: libnw.so.0: cannot open shared object file: No such file or directory
Initial topology in 0.17 seconds
Refining topology: 16 rounds ME-NNIs, 2 rounds ME-SPRs, 8 rounds ML-NNIs
Total branch-length 3.091 after 2.96 sec6, 1 of 15 splits
ML-NNI round 1: LogLk = -215438.545 NNIs 2 max delta 26.49 Time 4.82
GTR Frequencies: 0.2611 0.2384 0.2370 0.2635ep 12 of 12
GTR rates(ac ag at cg ct gt) 1.2737 28.3080 2.7326 0.7588 42.6211 1.0000
Switched to using 20 rate categories (CAT approximation)19 of 20
Rate categories were divided by 0.720 so that average rate = 1.0
CAT-based log-likelihoods may not be comparable across runs
Use -gamma for approximate but comparable Gamma(20) log-likelihoods
ML-NNI round 2: LogLk = -200542.115 NNIs 1 max delta 5.17 Time 19.45
ML-NNI round 3: LogLk = -200542.117 NNIs 0 max delta 0.00 Time 20.56
Turning off heuristics for final round of ML NNIs (converged)
ML-NNI round 4: LogLk = -200541.140 NNIs 0 max delta 0.00 Time 22.62 (final)
Optimize all lengths: LogLk = -200540.079 Time 23.39
Total time: 32.38 seconds Unique: 17/17 Bad splits: 0/14
make: *** [tree.newick] Error 127
make: Leaving directory 
....
and these were the files (excluding the samples folders) that were found in the out folder:
1079373 Aug 13 17:53 core.aln
69077520 Aug 13 17:53 core.full.aln
5548353 Aug 13 17:53 core.nway.tab
3604392 Aug 13 17:53 core.tab
536 Aug 13 17:53 core.txt
5103588 Aug 13 17:53 core.vcf
1103 Aug 13 16:03 denovo.tab
135 Aug 13 11:36 isolates.txt
64688 Aug 13 11:36 Makefile
1914 Aug 13 16:03 mlst.tab
4063591 Aug 13 11:36 ref.fa
 0 Aug 13 17:53 tree.newick

(I hope this gives enough of an idea of the situation) have you come across such an error? any ideas?

Thanks,
Yair

**Comment by motroy** [comment]
Found the culprit, 
"nw_order: error while loading shared libraries: libnw.so.0: cannot open shared object file: No such file or directory"

needed to recompile newick_tools (succeeded using version 1.3) to correct error in compilation of nw_order binary.
hope this helps others.
regards,
Yair

**Comment by tseemann** [comment]
@motroy yep you found the correct error.  good work on debugging it!
