### ISSUE TITLE
Shovill logs renamed

### ISSUE THREAD

**Issue by kwongj** [tseemann/nullarbor#112]
Since switching to `shovill`, the error logs are now labelled `00-shovill.log` and `60-spades.log`.

In the `Makefile`, this command fails:
```
mv ISOLATE/spades/spades.log ISOLATE/spades.log
rm -f -v -r ISOLATE/spades
```

Thus:
```
mv: cannot stat ‘ISOLATE/spades/spades.log’: No such file or directory
make: *** [ISOLATE/contigs.fa] Error 1
```

**Comment by tseemann** [comment]
@kwongj Nullarbor doesn't use Shovill - it still uses Megahit or Spades.

**Comment by tseemann** [comment]
I am considering writing a `nullarbor-mduphl.pl` or an `--mduphl` switch on the main script to do this automatically.
