### ISSUE TITLE
Run nullarbor components separately

### ISSUE THREAD

**Issue by kwongj** [tseemann/nullarbor#13]
More of a request rather than an issue:

Will it be possible to run each of the components separately?
Eg. reading a list of samples in samples.tab, suppose all the reads were already clipped, and already had  de novo assemblies and MLST, but you wanted to re-analyse a subset of the isolates using a different reference.
Could there be an option to run read metrics, snippy and snippy-core? I know I can run them separately, but would it be possible through the nullarbor command-line?

Thanks.

**Comment by tseemann** [comment]
Some of these things are probably possible simply by using the correct `Makefile` target, and/or by deleting the appropriate downstream file to trigger a reanalysis via the Makefile rules.

I think if you re-run nullarbor with the same --outdir and --force and change the reference, it will re-do everything it needs to, but it won't re-clip the reads as they don't depend on the reference.

If you only want MLST results, type `make mlst.tab`

if you want just assemblies, try `make denovo.tab`

Just ARG predictions, maybe `make abricate.tab`

**Comment by tseemann** [comment]
There is now a `make help` command to help with this stuff.
