### ISSUE TITLE
empty core.aln

### ISSUE THREAD

**Issue by Sam06060** [tseemann/nullarbor#131]
Hello,

I have recently attmepted to install nullarbor onto ubuntu 16 - process partially completes but running into the issue below:

convert tree.svg tree.gif
snp-dists -b core.aln > distances.tab
This is snp-dists 0.2
core.aln has size 0 bytes
ERROR: file contained no sequences
Makefile:746: recipe for target 'distances.tab' failed

Manged to get this working with the same isolate set on a different installation of nullarbor that looks comparable, so I know there isnt an issue with the isolates at least. Here it completed without error. Have tried updating freebayes and snippy version is 3.1 (which seems ok?) but no luck. initial install was done with brew.

Any help you can give would be great, thanks very much

Sam

**Comment by tseemann** [comment]
If `core.aln` has 0 bytes that usually means there was no core SNPs. This can happen easily when you have divergent isolates. But you said the exact same data worked on another setup, so I don't know.

Any other info you can provide?
