### ISSUE TITLE
nullarbor report not updating all files when using --force

### ISSUE THREAD

**Issue by kwongj** [tseemann/nullarbor#132]
When re-running nullarbor with `--force`, although some files in the report folder are updated, not all of them are:
```$ ll
total 64540
drwxr-xr-x.   2 jasonk1 domain^users     4096 Aug 21 10:03 ./
drwxr-xr-x. 521 jasonk1 domain^users    16384 Oct 16 22:22 ../
-rw-r--r--.   1 jasonk1 domain^users    42650 Oct 16 17:36 assembly.csv
-rw-r--r--.   1 jasonk1 domain^users 55661126 Aug 21 10:02 core.aln
-rw-r--r--.   1 jasonk1 domain^users    21605 Oct 16 17:36 core.csv
-rw-r--r--.   1 jasonk1 domain^users    61578 Oct 16 17:32 identification.csv
-rw-r--r--.   1 jasonk1 domain^users  7976871 Oct 16 17:38 index.html
-rw-r--r--.   1 jasonk1 domain^users      135 Oct 16 17:31 jobinfo.csv
-rw-r--r--.   1 jasonk1 domain^users    45454 Oct 16 17:32 mlst.csv
-rw-r--r--.   1 jasonk1 domain^users     1340 Oct 16 17:38 nullarbor.css
-rw-r--r--.   1 jasonk1 domain^users      236 Sep 27 15:37 pan.csv
-rw-r--r--.   1 jasonk1 domain^users   353372 Aug 21 10:32 pan.png
-rw-r--r--.   1 jasonk1 domain^users      127 Oct 16 17:36 reference.csv
-rw-r--r--.   1 jasonk1 domain^users    11285 Oct 16 17:33 resistome.csv
-rw-r--r--.   1 jasonk1 domain^users    35446 Oct 16 17:32 seqdata.csv
-rw-r--r--.   1 jasonk1 domain^users    31388 Oct 16 17:32 serotype.csv
-rw-r--r--.   1 jasonk1 domain^users  1497221 Oct 16 17:36 snpdist.csv
-rw-r--r--.   1 jasonk1 domain^users      432 Oct 16 17:38 tools.csv
-rw-r--r--.   1 jasonk1 domain^users    18161 Aug 21 10:02 tree.newick
-rw-r--r--.   1 jasonk1 domain^users   241670 Oct 16 17:34 virulome.csv
```

e.g. `tree.newick`, `pan.csv`, `pan.png`, `core.aln`.
Running `make report` fixes this, but would be nice if this was done automatically. The original Nullarbor command was:

```
/home/tseemann/git/nullarbor/bin/nullarbor.pl --name NM.all --mlst neisseria --ref ref/NM_M10208/NM_M10208.gbk --input all_samples.tab --outdir nullarbor.all --accurate --cpus 64 --force --keepfiles
```

**Comment by andersgs** [comment]
`make report` doesn't seem to fix `tree.newick` or `core.aln`.

**Comment by schultzm** [comment]
also, if running `nullarbor.pl --name xyz`
then `nullarbor.pl --force --name abc`
in the `Makefile`, the `make publish` command still points to the `xyz` name.  and the `report/index.html` line still contains the old name but the correct `--outdir` and `--indir`

**Comment by andersgs** [comment]
I have been poking around, and I think I am starting to get where some of these are arising.

The report used to be generated using `Report.pm`. But, it is now being generated in a very cool way, by using submodules for each section. I was looking at the `snptree.pm` submodule, and it seems to be missing two crucial `copy` commands that are on lines 420 and 421 of `Report.pm` that would force the update of the `core.aln` and `tree.newick` file in the `report` folder. Although, as I can see in `Report.pm` these files used to be renamed to match the report name. I had forgotten about that, although I prefer this approach of uniform naming across reports. Makes it easier to search and write scripts that consume the output.

Does that seem like I am going in the right direction @tseemann? This bug has come back to haunt me twice in the past week. :( I am hoping to try a PR in the next couple of days.

I am guessing some of the other issues here have a similar background.

**Comment by tseemann** [comment]
I am marking this as 'fixed' as so many things have changed in Nullarbor 2 and this specific problem is no longer clear.
