### ISSUE TITLE
bin/../plugins location error

### ISSUE THREAD

**Issue by Slugger70** [tseemann/nullarbor#135]
When I ran with the latest head from a brew install:

```
nullarbor.pl
```

Returned:

```
read_dir '/home/linuxbrew/.linuxbrew/bin/../plugins' - opendir: No such file or directory at /home/linuxbrew/.linuxbrew/Cellar/nullarbor/HEAD-1495981/bin/../perl5/Nullarbor/Plugins.pm line 20.
```

It seems as though it's looking for the plugins dir relative to the brew bin directory instead of the nullarbor one...

**Comment by tseemann** [comment]
Nice find!  Thank you.
