### ISSUE TITLE
Unable to install, is this still a 'live' project?

### ISSUE THREAD

**Issue by jb2cool** [tseemann/nullarbor#139]
I'm currently unable to install Nullarbor as emboss doesn't seem to be available via linuxbrew any more. I know there were other issues installing this at one point or another but is this ever likely to come back?

**Comment by tseemann** [comment]
Homebrew-science has moved:

```
brew tap brewsci/science
brew untap homebrew/science
brew upgrade prokka
```

**Comment by alantsangmb** [comment]
Hi, Torsten

I'm trying to upgrade nullabor, and got following warnings after I entered
>brew tap brewsci/science
>brew untap homebrew/science
>brew upgrade prokka

It warns perl is deprecated and blast is unable to be installed.

And I have also ran brew doctor, and the output is also appended. Please look at the mess I had made....I can't fix it.

########################## Output of brew upgrade prokka ##########################
Updating Homebrew...
Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/brewsci/homebrew-science/Formula/prokka.rb:13:in `<class:Prokka>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/brewsci/homebrew-science/Formula/prokka.rb:14:in `<class:Prokka>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/brewsci/homebrew-science/Formula/prokka.rb:15:in `<class:Prokka>'
Please report this to the brewsci/science tap!

==> Upgrading 1 outdated package, with result:
brewsci/science/prokka 1.12_1
==> Upgrading brewsci/science/prokka 
==> Installing dependencies for brewsci/science/prokka: blast
==> Installing brewsci/science/prokka dependency: blast
==> Downloading https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.6.0/ncbi
Already downloaded: /home/wgs/.cache/Homebrew/blast-2.6.0.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/5fa7f
Already downloaded: /home/wgs/.cache/Homebrew/blast--patch-ab6b827073df48a110e47b8de4bf137fd73f3bf1d14c242a706e89b9c4f453ae.diff
==> Patching
==> Applying blast-make-fix2.5.0.diff
patching file c++/src/build-system/Makefile.in.top
==> ./configure --prefix=/home/wgs/.linuxbrew/Cellar/blast/2.6.0_3 --without-deb


Last 15 lines from /home/wgs/.cache/Homebrew/Logs/blast/01.configure:
checking whether _LIBCPP_VERSION is declared... no
checking how to enable C++ '11 features in /home/wgs/.linuxbrew/Library/Homebrew/shims/linux/super/g++-4.8 ... -std=gnu++11
checking how to enable C '11 or at least '99 features in /home/wgs/.linuxbrew/Library/Homebrew/shims/linux/super/gcc-4.8 ... -std=gnu11 -fgnu89-inline
checking for dpkg-architecture... /usr/bin/dpkg-architecture
checking for gawk... gawk
checking for GNU make... make
checking for make... /usr/bin/make
checking whether ln -s works... yes
checking for ranlib... ranlib
checking for ar... ar cr
checking ranlib's effectiveness... neutral
checking for strip... strip
checking whether strip loses runtime type information... yes
Do you still want to proceed (at your own risk)? [y/N]
configure: error: Configuration has been canceled by user.

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.


############################# Output of brew doctor ############################

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/htslib/bgzf.h
  /usr/local/include/htslib/cram.h
  /usr/local/include/htslib/faidx.h
  /usr/local/include/htslib/hfile.h
  /usr/local/include/htslib/hts.h
  /usr/local/include/htslib/hts_defs.h
  /usr/local/include/htslib/hts_endian.h
  /usr/local/include/htslib/hts_log.h
  /usr/local/include/htslib/hts_os.h
  /usr/local/include/htslib/kbitset.h
  /usr/local/include/htslib/kfunc.h
  /usr/local/include/htslib/khash.h
  /usr/local/include/htslib/khash_str2int.h
  /usr/local/include/htslib/klist.h
  /usr/local/include/htslib/knetfile.h
  /usr/local/include/htslib/kseq.h
  /usr/local/include/htslib/ksort.h
  /usr/local/include/htslib/kstring.h
  /usr/local/include/htslib/regidx.h
  /usr/local/include/htslib/sam.h
  /usr/local/include/htslib/synced_bcf_reader.h
  /usr/local/include/htslib/tbx.h
  /usr/local/include/htslib/thread_pool.h
  /usr/local/include/htslib/vcf.h
  /usr/local/include/htslib/vcf_sweep.h
  /usr/local/include/htslib/vcfutils.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/htslib.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libhts.a

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /home/wgs/.linuxbrew/bin/c++
  /home/wgs/.linuxbrew/bin/cc
Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/abricate.rb:12:in `<class:Abricate>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/abricate.rb:13:in `<class:Abricate>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/abricate.rb:14:in `<class:Abricate>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/abricate.rb:15:in `<class:Abricate>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/abricate.rb:16:in `<class:Abricate>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/abricate.rb:17:in `<class:Abricate>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/abricate.rb:18:in `<class:Abricate>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/roary.rb:11:in `<class:Roary>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/nullarbor.rb:14:in `<class:Nullarbor>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/nullarbor.rb:15:in `<class:Nullarbor>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/nullarbor.rb:16:in `<class:Nullarbor>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/nullarbor.rb:17:in `<class:Nullarbor>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/nullarbor.rb:18:in `<class:Nullarbor>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/brewsci/homebrew-science/Formula/prokka.rb:14:in `<class:Prokka>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/brewsci/homebrew-science/Formula/mlst.rb:18:in `<class:Mlst>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/home/wgs/.linuxbrew/Library/Taps/brewsci/homebrew-science/Formula/mlst.rb:19:in `<class:Mlst>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/home/wgs/.linuxbrew/Library/Taps/brewsci/homebrew-science/Formula/megahit.rb:20:in `<class:Megahit>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/home/wgs/.linuxbrew/Library/Taps/brewsci/homebrew-science/Formula/mafft.rb:23:in `block in <class:Mafft>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/home/wgs/.linuxbrew/Library/Taps/brewsci/homebrew-science/Formula/mafft.rb:23:in `block in <class:Mafft>'
Please report this to the brewsci/science tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/home/wgs/.linuxbrew/Library/Taps/brewsci/homebrew-science/Formula/mafft.rb:23:in `block in <class:Mafft>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on :postgresql' is deprecated!
Use 'depends_on "postgresql"' instead.
/home/wgs/.linuxbrew/Library/Taps/brewsci/homebrew-science/Formula/emboss.rb:22:in `<class:Emboss>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on :mysql' is deprecated!
Use 'depends_on "mysql"' instead.
/home/wgs/.linuxbrew/Library/Taps/brewsci/homebrew-science/Formula/emboss.rb:23:in `<class:Emboss>'
Please report this to the brewsci/science tap!


Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install blast emboss curl gcc libpthread-stubs libxaw3d xdpyinfo snp-dists unzip

Run `brew missing` for more details.

**Comment by tseemann** [comment]
1. I notice you are installing in `/home/wgs/.linuxbrew`. If you are able to install in `/home/linuxbrew` your life will be a lot simpler as Liniuxbrew will be able to just install pre-compiled software.

2. The perl errors can be ignored, but you will need to install all the perl modules somehow. `brew install perl cpanminus ; cpanm Bio::Perl ... etc`

3. I am working on fixing all these issues.

4. @druvus is working on a Bioconda package for Nullarbor which should work much better

Sorry for the installation pain - but it's a complex piece of software.

**Comment by jb2cool** [comment]
Thanks for the update Torsten. At this point I just want a working install and I'll work backwards from there to get my ideal install. So rather than trying to install this on my desired Linux distro (CentOS) I'm perfectly happy to try whatever you use. I think I tried this fairly recently on a vanilla install of Ubuntu 16.04 but ran into some problems (this was one of the things that caused me to open the thread). I'll give this a shot again over the next few days and see how I get on

**Comment by tseemann** [comment]
Are you able to run Docker containers on a vanilla Ubuntu?

**Comment by jb2cool** [comment]
I should be able to install docker and run them yes, I don’t know if it’s there by default but installing stuff should be no issue

**Comment by nbargues** [comment]
@tseemann @druvus Hi , does the conda version of nullarbor is available soon ?

**Comment by druvus** [comment]
@nbargues It is a work in progress. I am currently waiting to get a conda-forge imagemagick version compatible with bioconda, see here  conda-forge/imagemagick-feedstock#10

Once this is merged I will continue with the nullarbor bioconda package.

**Comment by tseemann** [comment]
@druvus i am working on Nullarbor 2.x  now live on this github.
It does *not* need ImageMagick at all.
@slugger70 and I have a bioconda recipe nearly ready to go, once I make a 2.0.0 release.
