### ISSUE TITLE
Not accepting input file?

### ISSUE THREAD

**Issue by tarah28** [tseemann/nullarbor#141]
Hi Torsten - thanks so much for putting together this pipeline, I think it will be really useful for me!

I was finally able to get it installed using Stephen Turner and your answers to others for the Linuxbrew troubleshooting (thanks again), but when I try to run it, it's not recognizing my input but it's a tab separated file. I've tried modifying the samples.tab but nothing seems to help. Any suggestions?
# sample.tab looks like this:
"E1  /Desktop/nullarbor_test/E1_R1.fastq    /Desktop/nullarbor_test/E1_R2.fastq
E2  /Desktop/nullarbor_test/E2_R1.fastq    /Desktop/nullarbor_test/E2_R2.fastq
E3  /Desktop/nullarbor_test/E3_R1.fastq    /Desktop/nullarbor_test/E3_R2.fastq
E4  /Desktop/nullarbor_test/E4_R1.fastq    /Desktop/nullarbor_test/E4_R2.fastq
E5  /Desktop/nullarbor_test/E5_R1.fastq    /Desktop/nullarbor_test/E5_R2.fastq
E6  /Desktop/nullarbor_test/E6_R1.fastq    /Desktop/nullarbor_test/E6_R2.fastq"

# Command I ran was: 
`nullarbor.pl --name TESTING --mlst efaecalis --ref NC_004668.fna --input samples.tab --outdir test_out`

# Screen output was this: 
```
[11:20:18] Hello tl
[11:20:18] This is nullarbor.pl 1.28
[11:20:18] Send complaints to Torsten Seemann <torsten.seemann@gmail.com>
[11:20:18] Using reference genome: /home/tl/Desktop/nullarbor_test/NC_004668.fna
[11:20:18] Loaded 0 isolates:
[11:20:18] nullarbor.pl requires a mininum of 4 isolates to run (due to Roary)
```

**Comment by tseemann** [comment]
Here are some possibilities:

1. Are you sure `/Desktop` is in the root of your hard disk? Maybe you mean `/Users/tarah/Desktop` or `/home/tarah/Desktop` ?  

2. Some text editors convert tabs back into spaces when they save the file.

**Comment by tarah28** [comment]
It was #2! Thanks so much for the quick answer, I had no idea the text editor was reverting to spaces. Works great now!
