### ISSUE TITLE
Installing nullarbor

### ISSUE THREAD

**Issue by OrsonMM** [tseemann/nullarbor#145]
I tried to install nullarbor and i have these error 

$ brew tap tseemann/bioinformatics-linux
==> Tapping tseemann/bioinformatics-linux
Cloning into '/home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux'...
remote: Counting objects: 31, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 31 (delta 0), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (31/31), done.
Checking connectivity... done.
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/ngmaster.rb
uninitialized constant #<Class:0x00000003301fd0>::LanguageModuleRequirement
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/nullarbor.rb
Calling 'depends_on ... => :perl' is disabled!
There is no replacement.
/home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/nullarbor.rb:12:in `<class:Nullarbor>'
Please report this to the tseemann/bioinformatics-linux tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/snippy.rb
Calling 'depends_on ... => :perl' is disabled!
There is no replacement.
/home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/snippy.rb:12:in `<class:Snippy>'
Please report this to the tseemann/bioinformatics-linux tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/abricate.rb
Calling 'depends_on ... => :perl' is disabled!
There is no replacement.
/home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/abricate.rb:12:in `<class:Abricate>'
Please report this to the tseemann/bioinformatics-linux tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/pftools.rb
Calling 'depends_on :fortran' is disabled!
Use 'depends_on "gcc"' instead.
/home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/pftools.rb:11:in `<class:Pftools>'
Please report this to the tseemann/bioinformatics-linux tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/trim-galore.rb
Calling 'depends_on ... => :perl' is disabled!
There is no replacement.
/home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/trim-galore.rb:10:in `<class:TrimGalore>'
Please report this to the tseemann/bioinformatics-linux tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/gff3toembl.rb
Calling 'depends_on :python' is disabled!
Use 'depends_on "python@2"' instead.
/home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/gff3toembl.rb:10:in `<class:Gff3toembl>'
Please report this to the tseemann/bioinformatics-linux tap!
Or, even better, submit a PR to fix it!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/roary.rb
Calling 'depends_on ... => :perl' is disabled!
There is no replacement.
/home/ubuntu/.linuxbrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/roary.rb:10:in `<class:Roary>'
Please report this to the tseemann/bioinformatics-linux tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap tseemann/bioinformatics-linux: invalid syntax in tap!

**Comment by tseemann** [comment]
The homebrew community recently underwent a MAJOR change, and the current brew instructions will not work, I'm so sorry.

I am close to fixing things.  And also making a conda package.

Until then, can you try:

```
brew untap homebrew/science
brew tap brewsci/bio
brew tap brewsci/science
brew update
brew upgrade
brew install nullarbor
```
