### ISSUE TITLE
README install information is outdated

### ISSUE THREAD

**Issue by jkimsis** [tseemann/nullarbor#147]
The tap homebrew/science is deprecated, and when trying to do brew tap tseemann/bioinformatics-linux it gives multiple errors like this:

Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/nullarbor.rb
Calling 'depends_on ... => :perl' is disabled!
There is no replacement.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/nullarbor.rb:12:in `<class:Nullarbor>'
Please report this to the tseemann/bioinformatics-linux tap!
Or, even better, submit a PR to fix it!

**Comment by tseemann** [comment]
THanks for the reminder @jkimsis 

I am *very close* to having a new Nullarbor package in `brewsci/bio` and bioconda!

**Comment by jb2cool** [comment]
I'd have a few users that would be very happy with this (Conda especially). Fingers crossed that it'll be happy on CentOS too.

**Comment by tseemann** [comment]
We use RHEL 7.x (Centos 7.x) here so it should.

**Comment by DrAnneJ** [comment]
Hi, Nullarbor is awesome but it was indeed very difficult to install...I will be very happy to use a new version easier to install ;-) And again thank you for your tools that are so usefull in microbial genomics !
