### ISSUE TITLE
Can I run afa-pairwise.pl independently?

### ISSUE THREAD

**Issue by raymondkiu** [tseemann/nullarbor#148]
Hello

Wondering if this script can be run independently on Snippy outputs (not using nullarbor pipeline)? If the answer is yes, can you roughly direct how to do this? 

Appreciate your help.

Raymond

**Comment by tseemann** [comment]
Raymond

You can run it independently but I have written a replacement called snp-dists . It is on GitHub and has instructions and examples 

Torsten
