### ISSUE TITLE
Brew installable 

### ISSUE THREAD

**Issue by mscook** [tseemann/nullarbor#16]
brew install fails due to a dependency of ImageMagic -

Clean Ubuntu 14.04 install.

```
...
sudo apt-get -y install build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev python-pip libpng-dev unzip flex bison python-dev libpng-dev pkg-config libcairo2-dev perl-doc expect

sudo perl -MCPAN -e "CPAN::Shell->notest('install', 'Bio::Perl')"
sudo cpan -i Moo
sudo cpan -i Spreadsheet::Read
sudo cpan -i SVG::Graph
...
brew install nullarbor

Installing dependencies for nullarbor: libcroco, librsvg, imagemagick
==> Installing nullarbor dependency: libcroco
==> Downloading http://ftp.gnome.org/pub/GNOME/sources/libcroco/0.6/libcroco-0.6.8.tar.xz
Already downloaded: /home/vagrant/.cache/Homebrew/libcroco-0.6.8.tar.xz
==> ./configure --prefix=/home/vagrant/.linuxbrew/Cellar/libcroco/0.6.8 --disable-Bsymbolic
installed software in a non-standard prefix.

Alternatively, you may set the environment variables CROCO_CFLAGS
```

Log is at: https://gist.github.com/4c13e3e099957a6c4cc9

**Comment by mscook** [comment]
ps> 

```
sudo apt-get install imagemagick
# see if this pulls down req'ed libs
brew install nullarbor

==> Installing nullarbor dependency: libcroco
==> Downloading http://ftp.gnome.org/pub/GNOME/sources/libcroco/0.6/libcroco-0.6.8.tar.xz
Already downloaded: /home/vagrant/.cache/Homebrew/libcroco-0.6.8.tar.xz
==> ./configure --prefix=/home/vagrant/.linuxbrew/Cellar/libcroco/0.6.8 --disable-Bsymbolic
installed software in a non-standard prefix.

Alternatively, you may set the environment variables CROCO_CFLAGS
and CROCO_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by tseemann** [comment]
That's wierd. I don't have libcroco installed. It isn't a dep of imagemagick. It does install for me cleanly, but i'm guessing that the brew recipe for it assumes some Mac inclusion that we don't have on Linux.

**Comment by mscook** [comment]
yeah. I just spin up a clean vagrant box for everything these days and
provision using a shell script.

On 2 June 2015 at 16:33, Torsten Seemann <notifications@github.com> wrote:

> That's wierd. I don't have libcroco installed. It isn't a dep of
> imagemagick. It does install for me cleanly, but i'm guessing that the brew
> recipe for it assumes some Mac inclusion that we don't have on Linux.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tseemann/nullarbor/issues/16#issuecomment-107825435>.
>



-- 
================================
Mitchell Jon Stanton-Cook <https://github.com/mscook> (@Bio_mscook)

Teaching Fellow &
Software Engineer/System Administrator
Beatson Microbial Genomics Group <http://beatsonlab.com>
University of Queensland
Brisbane, Australia
--------------------------------------------------------
Software Carpentry Workshop
Lead Instructor
UQ Bootcamp 02-03 July 2015  <http://bio-swc-bne.github.io/2015-07-02-UQ/>
--------------------------------------------------------
Co-organiser
2015 HealthHack Brisbane
October 23-24-25 2015 <http://www.healthhack.com.au>
================================

**Comment by tseemann** [comment]
So the problem is the libcroco formula?

You'll have to file an upstream issue.

**Comment by tseemann** [comment]
The simplest solution is to just checkout the git repository - all binaries are included!
