### ISSUE TITLE
iqtree ntmax options issue in iqtree.sh

### ISSUE THREAD

**Issue by ramjet10** [tseemann/nullarbor#165]
Not sure if this is just something with my install (and having 32 thread cpu) but I have had some funny issues with iqtree not liking the options being set for the number of threads in the iqtree.sh script under the plugins folder.

I have the nullarbor version 2 installed (everything from conda except for a few bits and pieces) on Ubuntu 16.04.

Everything works, but the pipeline halts on the iqtree.sh script as iqtree didn't like the -ntmax option. I thought this was just due to the version of iqtree in conda. Indeed the conda version of iqtree I had installed was old and the -ntmax option is only in the latest version of iqtree. I removed the iqtree version and replaced with the latest version that has the -ntmax option. But strangely this still didn't fix it for some reason, instead iqtree spits out a message indicating I should use -nt AUTO because I have 32 cores.

Anyway, editing the iqtree.sh script to use -nt AUTO, instead of the variable defined after -ntmax, fixes it and everything runs perfectly. Very fast as well. 

Thanks, 

Josh

**Comment by ramjet10** [comment]
Sorry I forgot to mention another change I made to the script - to change the shebang to #!/bin/bash rather than sh. I didn't think this was that important initially but I just installed everything again on another computer (Ubuntu 18.04, i7-4790K) and the -nt AUTO change alone didn't work. 
After I changed the shebang, I also test if I actually needed the -nt AUTO change and found that in this case the -nt AUTO change wasn't necessary, as long as I was using the latest version of iqtree (so it has -ntmax option).
Maybe there is something going wrong with the variables being set using the default dash shell on ubuntu so they don't get properly set unless you specify bash. I don't really know with my limited computer knowledge :)

**Comment by bfssi-forest-dussault** [comment]
Just wanted to add that I also needed to change the shebang from #!/bin/sh to #!/bin/bash in iqtree.sh in order to have it run. I was getting an "illegal option pipefail" error which was fixed by switching over. I'm running Ubuntu (16.04) which like ramjet10 said defaults to dash when calling /bin/sh.

**Comment by tseemann** [comment]
I was using bash for assembler and taxoner plugins, but not for treebuilder. I've fixed this. 

Thank you for the detailed forensics and the information about `dash` !
