### ISSUE TITLE
Could not find 'fq'  (manually installation of nullarbor v2)

### ISSUE THREAD

**Issue by manuss11** [tseemann/nullarbor#170]
Hello, I´m trying to install nullarbor v2 manually, step by step by running ./nullarbor/bin/nullarbor.pl -- check, following installation guide and then installing the required programs or files. But I'm blocked on this error:

ERROR: **Could not find 'fq'.** Please install it and ensure it is in the PATH.

I don't know what 'fq' means here. I would appreciate some help!

Thanks a lot!

**Comment by andersgs** [comment]
I suspect you need to add `./nullarbor/bin` to your PATH variable. `fq` is distributed as part of Nullarbor.

Try: `export PATH=/path/to/nullarbor/bin:$PATH` and then try `nullarbor.pl` again. You should not need to call it by using the whole path that way.

Good luck.

**Comment by tseemann** [comment]
@andersgs is correct, you need to put `nullabor/bin` in your PATH.

I will leave this issue open and add a step to the install instructions.

**Comment by manuss11** [comment]
You're right! This solves the problem. Thank you so much ;)
