### ISSUE TITLE
Skippy 4.0 bug (Can not find required 'vcffirstheader' in PATH)

### ISSUE THREAD

**Issue by manuss11** [tseemann/nullarbor#171]
Hello, while running nullarbor it stopped and showed the following error: 
Can not find required 'vcffirstheader' in PATH
I  found that it is a bug from the 4.0 version of skippy. I tried to downgrade to 3.2v, but I am not able to run nullarbor with skippy 3.2.
How could I solve this issue? Could I return the pipeline from that step?

Thanks

**Comment by stephenturner** [comment]
I ran into this issue a while back, wrote this hack years ago to fix it.
Not sure if it'll still work.
https://gist.github.com/stephenturner/005d4e4e322b8cf5b991d1d357527859#file-nullarbor-install-ubuntu1404-sh-L194

**Comment by tseemann** [comment]
SNippy 4 in conda is a mistake.  Someone added it prematurely, It does not work. You'll need to use github clone method.
