### ISSUE TITLE
How to install Nullarbor 1 with brew

### ISSUE THREAD

**Issue by manuss11** [tseemann/nullarbor#173]
Hi, I have other issue opened about installing and running nullarbor 2, so in the meanwhile of solving that  I tried to install Nullarbor 1  to be able to work with my data. I followed README.V1.md instructions: 
```
brew tap homebrew/science
brew tap tseemann/bioinformatics-linux
brew install nullarbor --HEAD
```
But it doesn't work (ERROR: Calling 'depends_on ... => :perl' is disabled!)

Then, I tried other instructions given by Mr. Seemann in another issue:
```
brew untap homebrew/science
brew tap brewsci/bio
brew tap brewsci/science
brew update
brew upgrade
brew install nullarbor
```
But it still doesn't work (Error: No available formula with the name "nullarbor") 

I'm feeling a bit defeated, because I'm  new in bioinformatics and each step is quite difficult. Hopefully someone could help me. Thanks a lot and sorry for my insistence.

**Comment by tseemann** [comment]
I am no longer supporting Nullarbor 1.

You are right that those new instructions you found are now out of date. It was during a difficult transition time for the brew science project.

Nullarbor 2 will need Snippy 4.  Both of them are close to release.

I am sorry they are not able to be installed easily yet.   When they are released they will work in Bioconda and Homebrew, but this well be another month or so.

**Comment by manuss11** [comment]
OK, I would try this way. Thanks for the help!

**Comment by tseemann** [comment]
You've come into a time of major flux in the Nullarbor project, so you are not alone in having some issues.  Thank you for your patience.
