### ISSUE TITLE
centrifuge version not etected properly

### ISSUE THREAD

**Issue by jkibilds** [tseemann/nullarbor#181]
When running `./nullarbor/bin/nullarbor.pl --check` I got this:
`[14:56:07] Parsed version '3' from '/home/customer/anaconda3/envs/nullarbor/bin/centrifuge-class version 1.0.3-beta'` which is obviously not correct.
Centrifuge was installed via conda.

**Comment by tseemann** [comment]
I seem to get this:

```
[12:38:42] Parsed version '1.0' from '/home/linuxbrew/.linuxbrew/bin/../Cellar/centrifuge/1.0.3/bin/centrifuge-class version 1.0.3-beta'
```
