### ISSUE TITLE
Tree doesn't display bootstraps or put them in exported Newick

### ISSUE THREAD

**Issue by tseemann** [tseemann/nullarbor#182]
Via @WillPitchers

**Comment by schultzm** [comment]
+1.  Feature request, let the download link to `core.newick`, which has the bb and alrt values as `bb_alrt` on the branches.

**Comment by tseemann** [comment]
@schultzm can you find out if http://phylocanvas.org/ supports bootstraps?

**Comment by tseemann** [comment]
Ok, added `core.newick` to files in report folder and added `Download: core.newick` at bottom of panel.

Thank you for your patience.
