### ISSUE TITLE
Check input reads are gzipped (suggestion)

### ISSUE THREAD

**Issue by telatin** [tseemann/nullarbor#186]
It would be nice to check if **FASTQ reads** are **gzipped** before producing the Makefile, as supplying an "input.tab" file with uncompressed reads will not result in throwing errors/warnings: the process will be blocked executing the pipeline:
```
fq --quiet --ref ref.fa SN4/R1.fq.gz SN4/R2.fq.gz > SN4/yield.tab
Calculating depth, using size 5015899
read1="SN2/R1.fq.gz" read2="SN2/R2.fq.gz" outdir="SN2" cpus=4 opts="" /home/ubuntu/data/import/salmonella/sra/nullarbor/bin/../plugins/assembler/skesa.sh
skesa --use_paired_ends --gz --fastq SN2/R1.fq.gz,SN2/R2.fq.gz --cores 4 --memory 16 --contigs_out SN2/contigs.fa

Invalid fastq file format in SN2/R1.fq.gz
```

Thanks!
Andrea

**Comment by tseemann** [comment]
I have asked the SKESA authors multiple times to handle the .gz transparently :-/
The simplest solution for now is to change `--assembler` to `spades`, `shovill` etc.
I will patch the plugin script for SKESA to be smarter.
