### ISSUE TITLE
skewer taking a long time ...

### ISSUE THREAD

**Issue by kwongj** [tseemann/nullarbor#19]
Is it usual for skewer to take 8.5 minutes to clip reads? (514 seconds for 5,619,342 MiSeq reads using 64 cpus). I thought I remember skewer running much faster than that eg. 30 seconds previously.

**Comment by tseemann** [comment]
Was it actually using all 64 cores?

Or was there disk contention on your storage system from other nodes, and it was waiting on I/O ?

You can use "nfsiostat 3" to look at dynamic NFS transfer rates.

**Comment by tseemann** [comment]
I noticed today Skewer was using only 2-3 cores when it used to use 16+.  It didn't seem to be too much slower but something is different.

**Comment by tseemann** [comment]
I have moved to `trimmomatics` now.
