### ISSUE TITLE
Error in nw_display in nullarbor 2 (liblua-5.1.so)

### ISSUE THREAD

**Issue by manuss11** [tseemann/nullarbor#190]
Hello again, sorry about my insistence. I found another error in the pipeline, and I don't know how to fix it:

```
Date and Time: Tue Sep  4 09:20:49 2018
nw_display -S -s -w 1024 -l 'font-size:12;font-family:sans-serif;' -i 'opacity:0' -b 'opacity:0' -v 16 core.newick > core.svg
nw_display: error while loading shared libraries: liblua-5.1.so: cannot open shared object file: No such file or directory
Makefile:127: recipe for target 'core.svg' failed
make: *** [core.svg] Error 127
make: *** Deleting file 'core.svg'
make: *** Waiting for unfinished jobs....

```
Thanks a lot for the patience

**Comment by tseemann** [comment]
You need to reinstall `newick-utils` as it is broken because you are mussing the `lua` libraries.

How did you install all the dependences?

yum/apt, brew, conda, manually ?

**Comment by manuss11** [comment]
I installed newick-utils manually. I would try conda. Sorry about all that questions, it is obvious that I have problems with installing packages because of my limited knowledge with linux/ubuntu :(

**Comment by tseemann** [comment]
That's ok i understand.

nullarbor is not in conda yet, but all of the dependencies are.

maybe try `apt-get install liblua-dev` or `lua-dev` etc first

**Comment by manuss11** [comment]
I tried installing both packages, and finally it works!  I`m so grateful Mr. Seemann :)

**Comment by tseemann** [comment]
You're welcome.
