### ISSUE TITLE
Set trimmomatic configuration in Nullarbor2

### ISSUE THREAD

**Issue by manuss11** [tseemann/nullarbor#193]
Hello, 
I would like to know if it is possible to set the trimmomatic functions in nullarbor 2. I set the option `--trim ON`, but I don´t know what it does indeed. I would like to do that to my raw fastq files:

`ILLUMINACLIP:adapters-trimmo/TruSeq3-PE-2.fa:2:30:10 SLIDINGWINDOW:4:20 MINLEN:35`

Thanks a lot

**Comment by tseemann** [comment]
You can edit your conf/nullarbor.conf file to change that.
