### ISSUE TITLE
tree builder fails

### ISSUE THREAD

**Issue by prmac** [tseemann/nullarbor#199]
Hi Torsten,

nullarbor runs fine for several hours and outputs a folder per isolate plus a roary folder.  I am running into the following error and at a loss for how to fix it.

Running `make` from the run directory gives the following.

```
aln="core.aln" tree="core.newick" cpus=4 opts="" /home/ubuntu/software/nullarbor/bin/../plugins/treebuilder/iqtree_fast.sh
ERROR: Invalid "-redo" option.
Makefile:128: recipe for target 'core.newick' failed
make: *** [core.newick] Error 2
```

[Makefile for reference](https://github.com/tseemann/nullarbor/files/2400725/Makefile.txt)

**Comment by tseemann** [comment]
You need to upgrade iqtree to 1.6.5 version (or a version with `-redo` option)

Or use `--treebuilder fasttree` instead.
