### ISSUE TITLE
symbolic links

### ISSUE THREAD

**Issue by dwilkin799** [tseemann/nullarbor#203]
Dear Pr Seemann,
I managed to get the latest version of nullarbor working on an Ubuntu 18 VM, which I run through VirtualBox.
Just thought I would raise one potential issue here.
I notice that you have favoured the use of symbolic links over copying files in nullarbor 2 - good idea to save on disk usage.
However, some virtual machines (it may be VirtualBox specific, I haven't checked) do not allow you to create symbolic links on shared drives.... and I favour the use of shared data drives when using a VM in order to keep the VM image file small.
I managed to get around this on my system simply by replacing the use of 'ln' with 'cp', but I can't find them all - specifically if you do not call "--trim", I'm not sure where the symbolic links to the reads files are created.

This was the main problem I encountered getting it installed, and I did each of the dependencies individually as local installs with shortcuts in usr/bin... so I was expecting more issues - so fantastic work on the update of nullarbor! this is a massive improvement over nullarbor1.

**Comment by tseemann** [comment]
Yes i have had a few msgs about symlink problems. I didn't anticipate that so many people were using CIFS volumes or shared Windows/Mac drives, especially given Nullarbor takes a long time to run.

I am thinking of switching it back to copying files.

**Comment by tseemann** [comment]
@dwilkin799 you can now use `nullarbor.pl --link-cmd 'cp'` or `make LINK="cp"`
