### ISSUE TITLE
Mash 2.1 error in nullarbor v2.0.20181010: option p cannot be used with r

### ISSUE THREAD

**Issue by ropolomx** [tseemann/nullarbor#207]
Hi Torsten,
Thanks for the amazing work with `nullarbor`! I am very excited to work with it. I am trying to run `nullarbor` using `shovill ` as the assembler. However, I find that there is an error that I suspect is connected to using `mash` 2.1. When I try using `shovill` in a different `conda` environment that has `mash` 2.0, `shovill` runs successfully However, since `nullarbor` needs `mash` version 2.1, I can't use version 2.0. 

The error message is below. I can show you the complete log if necessary.
```
[shovill] Read stats: min_len = 30
[shovill] Read stats: avg_len = 141
[shovill] Read stats: total_bp = 86125082
[shovill] Read stats: max_len = 151
[shovill] Estimating genome size with 'mash'
[shovill] Running: mash sketch -o /tmp/X1xwU4nQ88/sketch -p 11 -k 32 -m 3 -r \/home\/jinl\/Long\/AMR\/Sequences_for_uploads\/Mh_test_shovill\/105N\/R1\.fq\.gz 2>&1 | sed 's/^/[mash] /' | tee -a shovill.log
[mash] ERROR: The option p cannot be used with r.
[shovill] Could not determine genome size from ''
Makefile:130: recipe for target '105N/contigs.fa' failed
```

**Comment by esteinig** [comment]
Hi @ropolomx - I ran into this issue as well. Torsten opened an issue [here](https://github.com/marbl/Mash/issues/99). I fixed this temporarily by reverting back to the Mash 2.0, for instance in conda with force uninstall (to prevent removing Shovill dependency) and reinstall with correct version:

```bash
conda remove -n your_env mash
conda install -c conda-forge -c bioconda mash=2.0
```

**Comment by tseemann** [comment]
This was fixed in shovill here: https://github.com/tseemann/shovill/commit/3fe8e193a8c1f1bf9a1cfc1a79c86b1bda5969e1

I tagged the 1.0.4 release:
https://github.com/tseemann/shovill/archive/v1.0.4.tar.gz

The brew package is up to date, but someone will need to update the conda one.

**Comment by ropolomx** [comment]
Thanks @esteinig and @tseemann for your comments! I installed the 1.0.4 release of `shovill` for the moment. That worked, and that is what I am using to run `nullarbor`. Unfortunately, downgrading to Mash 2.0 within the conda environment didn't work since `nullarbor` needs Mash 2.1. Thanks again for your suggestions!

**Comment by esteinig** [comment]
Ah, apologies @ropolomx tested it on Shovill directly not Nullarbor :) Glad to see the fix @tseemann, fast as always!

**Comment by druvus** [comment]
Shovill is now updated also in bioconda.

**Comment by ropolomx** [comment]
Thanks @esteinig for the conda solution! It did work for the environment where I was working with `shovill` and not `nullarbor`. Thanks @druvus for letting us know! Very much appreciated!!
