### ISSUE TITLE
Name and length collide in the LOCUS line

### ISSUE THREAD

**Issue by shimbalama** [tseemann/nullarbor#208]
Hi Torst,

This happened only ~20 times in 2083 gbks and in only one contig per sample as far as I can tell. When parsing with Biopython I get 'Name and length collide in the LOCUS line:' 

Heres an example: LOCUS       ERS180486.8898_1_84.11010952 bp    DNA     linear       21-JUL-2018

I guess you'll just say 'use short names' but maybe you could write something to handle this issue.

**Comment by tseemann** [comment]
I can't handle it, because the Genbank standard can't encode longer IDs!
So Bioperl and every tool in the world will fail to parse it.
