### ISSUE TITLE
--mlst flag is not being passed on to mlst call

### ISSUE THREAD

**Issue by andersgs** [tseemann/nullarbor#209]
It seems `--mlst` flag is not being passed on to `mlst` call. 

## Command line:

```
nullarbor.pl --name Test --ref Bpseudo_M1.gbk --input input.txt --outdir nullarbor --mlst bpseudomallei --force
```

## Makefile

```
...
MLST := mlst
...
mlst.tab : $(FASTAREF) $(CONTIGS)
        mlst $^ > $@
```

**Comment by tseemann** [comment]
You are right... this could be tricky due to the static nature of my new Makefile.

**Comment by tseemann** [comment]
This also uncovered another bug where i define `MLST := mlst ...` but don't use it!
