### ISSUE TITLE
Undefined subroutine &main::path called at /home/roy/nullarbor/bin/nullarbor.pl line 322, <DATA> line 138.

### ISSUE THREAD

**Issue by rgranit** [tseemann/nullarbor#211]
When attempting to run nullarbor I encounter the following error:
`Undefined subroutine &main::path called at /home/roy/nullarbor/bin/nullarbor.pl line 322, <DATA> line 138.`

Any suggestions?

Thanks

**Comment by rgranit** [comment]
If I harcode the `$relout` variable I can get the nullarbor to work.. so I guess there is some issue with line #322 at `nullarbor.pl` not sure if it's just in my env.. @tseemann ?

**Comment by tseemann** [comment]
Do you have `Path::Tiny` perl module installed?

**Comment by tseemann** [comment]
Try `cpan Path::Tiny` to install it.

**Comment by rgranit** [comment]
Thanks! I will try that out
