### ISSUE TITLE
Nullarbor report failed

### ISSUE THREAD

**Issue by mdhitch** [tseemann/nullarbor#212]
I cannot seem to output an html report. All csv files within the report output directory exist, however nullarbor exits with....

**_

> Can't open /home/ubuntu/extra/core.nway.tab in Nullarbor::Tabular::load
> Makefile:48: recipe for target 'report/index.html' failed
> make: *** [report/index.html] Error 1

_**

Any ideas on what is wrong and how I can amend it?

Cheers

**Comment by tseemann** [comment]
How did you install Nullarbor?
