### ISSUE TITLE
Using one of the samples as reference.gbk

### ISSUE THREAD

**Issue by manuss11** [tseemann/nullarbor#214]
Hello, I'm running Nullarbor2 and I want to use one of our annotated strains (by a previous nullarbor run) as reference, but I found the following error:

--------------------- WARNING ---------------------
`MSG: Bad LOCUS name?  Changing [NODE_1_length_1250606_cov_31.5067721250606] to 'unknown' and length to 'NODE_1_length_1250606_cov_31.5067721250606`

`Duplicate sequence unknown in /home/qiime2/Isolate_k53/contigs.gbk`

It seems that the contigs.gbk file obtained by nullarbor did not work for snippy analysis 
Which file from the nullarbor output should be used to employ as reference in a subsequent  nullarbor analysis? I see that the file contigs.fa works, but then snippy analysis doesn't include genes info.

Thanks a lot

**Comment by tseemann** [comment]
The contig names produced by Spades are too long. Genbank requires contig IDs to be < 37 characters long.  Try manually running prokka with `--compliant` mode on the contigs you want to use as a reference.

**Comment by manuss11** [comment]
Thanks a lot, it works fine!
