### ISSUE TITLE
Kraken unclassified

### ISSUE THREAD

**Issue by thushandesilva** [tseemann/nullarbor#219]
Hi, 
nullarbor appears to be running OK (dependency check also passed at start), but the one issue is that the Kraken output does not appear to be working. All are unclassified. This is the Kraken aspect from the log from one of the samples. 
Thanks
Thushan

read1="SW101A/R1.fq.gz" read2="SW101A/R2.fq.gz" outfile="SW101A/kraken.tab" cpus=4 opts="" /home/ubuntu/miniconda3/bin/../plugins/taxoner/kraken.sh
/home/ubuntu/miniconda3/libexec/classify: invalid option -- 'd'
Usage: classify [options] <fasta/fastq file(s)>

Options: (*mandatory)
* -H filename      Kraken 2 index filename
* -t filename      Kraken 2 taxonomy filename
* -o filename      Kraken 2 options filename
  -q               Quick mode
  -M               Use memory mapping to access hash & taxonomy
  -T NUM           Confidence score threshold (def. 0)
  -p NUM           Number of threads (def. 1)
  -Q NUM           Minimum quality score (FASTQ only, def. 0)
  -P               Process pairs of reads
  -S               Process pairs with mates in same file
  -R filename      Print report to filename
  -m               In comb. w/ -R, use mpa-style report
  -z               In comb. w/ -R, report taxa w/ 0 count
  -n               Print scientific name instead of taxid in Kraken output
  -C filename      Filename/format to have classified sequences
  -U filename      Filename/format to have unclassified sequences
  -O filename      Output file for normal Kraken output

**Comment by tseemann** [comment]
My guess is you are using Conda?
I think the kraken and kraken2 packages used to be broken - they both tried to install their own `classify` binary into the PATH.
Try `conda update --all` to get the newer packages, or `conda install --force kraken2`
CC: @drpowell

**Comment by thushandesilva** [comment]
Thank you. Yes I am using conda. Let me try updating as suggested.
