### ISSUE TITLE
Can not read sequence #1 of 5

### ISSUE THREAD

**Issue by mars3680** [tseemann/nullarbor#220]
Dear tseemann

my sample.tab is 

Isolate_1			/home/mars/Documents/Vibrios/19085D-01-01_S165_L007_R1_001.fastq.gz			/home/mars/Documents/Vibrios/19085D-01-01_S165_L007_R2_001.fastq.gz
Isolate_2			/home/mars/Documents/Vibrios/19085D-01-02_S166_L007_R1_001.fastq.gz			/home/mars/Documents/Vibrios/19085D-01-02_S166_L007_R2_001.fastq.gz
Isolate_3			/home/mars/Documents/Vibrios/19085D-01-03_S172_L007_R1_001.fastq.gz			/home/mars/Documents/Vibrios/19085D-01-03_S172_L007_R2_001.fastq.gz	
Isolate_4			/home/mars/Documents/Vibrios/19085D-01-04_S167_L007_R1_001.fastq.gz			/home/mars/Documents/Vibrios/19085D-01-04_S167_L007_R2_001.fastq.gz
Isolate_5			/home/mars/Documents/Vibrios/19085D-01-05_S168_L007_R1_001.fastq.gz			/home/mars/Documents/Vibrios/19085D-01-05_S168_L007_R2_001.fastq.gz
Isolate_6			/home/mars/Documents/Vibrios/19085D-01-06_S169_L007_R1_001.fastq.gz			/home/mars/Documents/Vibrios/19085D-01-06_S169_L007_R2_001.fastq.gz
Isolate_7			/home/mars/Documents/Vibrios/19085D-01-07_S170_L007_R1_001.fastq.gz			/home/mars/Documents/Vibrios/19085D-01-07_S170_L007_R2_001.fastq.gz
Isolate_8			/home/mars/Documents/Vibrios/19085D-01-08_S171_L007_R1_001.fastq.gz			/home/mars/Documents/Vibrios/19085D-01-08_S171_L007_R2_001.fastq.gz

As you can see, each lines are separated like you say in nullarbor page, but my prompt ansrwer is:

[10:02:07] Hello mars
[10:02:07] This is nullarbor.pl 2.0.20181010
[10:02:07] Send complaints to Torsten Seemann
[10:02:07] Scanning --ref for problematic sequence IDs...
[10:02:07] Using reference genome: /home/mars/Documents/Vibrios/NC_004603.gbk
[10:02:07] ERROR: Isolate 'Isolate_1' - can not read sequence #1 of 5 files: ''

Finally, my command line is: 

nullarbor.pl --name Vp --mlst vparahaemolyticus --ref NC_004603.gbk --input samples.tab --outdir Vp_report

I installed all programs and database, everything is OK! And at this point, I don't know what I do.

Thank in advance!

**Comment by tseemann** [comment]
@mars3680 are the columns in samples.tab TAB separated?

Can you show me what `cat -A samples.tab` looks like?

**Comment by deearahman** [comment]
Hi Torsten,

I'm having the same problem. I've managed to download and all seems ok until running the actual program.

nullarbor.pl --name NULLARBOR --mlst efaecium --ref LR135278.fasta --input sample.tab --outdir nullarbor_output

[09:20:02] ERROR: Isolate 'DBWGS06_S3_18DS9259_MPS117' - can not read sequence #1 of 1 files: 'Raw/WGS_Analysis/Raw/MPS117_S3_L001_R1_001.fastq.gz'

I've checked that it is tab file cat -A sample.tab

DBWGS06_S3_18DS9259_MPS117^IRaw/MPS117_S3_L001_R1_001.fastq.gz^I/Raw/MPS117_S3_L001_R2_001.fastq.gz$


Thanks
