### ISSUE TITLE
R versioning and Roary

### ISSUE THREAD

**Issue by pjbiggs** [tseemann/nullarbor#224]
Hi,

I am using Nullarbor2 (v. 2.0.20181010; pre-Conda) installed into am Ubuntu 18.04 VM.  I was using R 3.4.4 and everything was working fine.  I have updated to R 3.6.1, and now my roary script is broken, and so therefore is my nullarbor:

```
$ roary
Can't locate Bio/Roary/CommandLine/Roary.pm in @INC (you may need to install the Bio::Roary::CommandLine::Roary module) 
............
BEGIN failed--compilation aborted at /usr/local/bin/roary line 17.
```

I have looked at having multiple R versions on my VM as way to sort this out.  Is there a simple way to try to restore the situation by keeping my updated R version?

Thanks in advance,

Patrick

**Comment by tseemann** [comment]
I don't think R is the problem. The error is from Perl. I think Perl has upgraded and you've lost your local library path. You need to reinstall roary `cpan Bio::Roary` perhaps. This is not a Nullarbor issue. All the best!
