### ISSUE TITLE
different CDS numbers

### ISSUE THREAD

**Issue by skaralegui** [tseemann/nullarbor#228]
Hi,
I am comparing 8 _S. marcescens_ strains and ran Nullarbor for it. When comparing my assembly table report (the CDS column) to the numbers that appeared in the pangenome graphic (to the right), they do not match. Are both data showing the CDS number of each strain or should I understand them as different things? If so, what is the number of the pangenome graphic meaning?

Thank you in advance!
![pan](https://user-images.githubusercontent.com/53474542/62124105-acdf5980-b2c9-11e9-9854-e10361122208.png)
[report.pdf](https://github.com/tseemann/nullarbor/files/3446463/report.pdf)

**Comment by tseemann** [comment]
The plot is a direct picture of what is in the roary `gene_presence_absence.csv` file. It's the number of ortholog clusters each isolate has members in. If there are gene duplications (paralogs) then they often only count as 1 ortholog cluster. So the number on the right will always be LESS than the number of CDS in the sample.

**Comment by skaralegui** [comment]
Thank you for your response. I understand now and the explanaition makes sense. Nevertheless, I found a problem: the number of CDS in the assembly report (I have attached it in the previous message) is smaller than the number of the ortholog clusters that appears in the pangenome graphic, just the opposite as you have said...

**Comment by tseemann** [comment]
@skaralegui can you email me the `genome_presence_absence.csv` file?
