### ISSUE TITLE
--force option sometimes re-performs mapping and SNP calls

### ISSUE THREAD

**Issue by kwongj** [tseemann/nullarbor#23]
I want to run nullarbor on a subset of my samples that have already been run through nullarbor.
For organisation purposes, and for ease of viewing of just that subset for external parties, I want to regenerate the nullarbor webpage report, otherwise I would have just run snippy-core.

I created a new project folder, with symlinks to the sample folders in the main nullarbor directory. I created a new samples.tab file with the list of isolates in the subset for analysis and generated a new makefile from this.

However, when running nullarbor from this new project folder with --force, nullarbor repeats the mapping and SNP calling process. Why is this? The reference is unchanged.

**Comment by tseemann** [comment]
I think the symlinks are the problem, but .  They have a new date on them, and `make` things it has to re-do everything.  

Can you just `mv report report.old` and re-run within the same folders?  

I intend to change the folder layout of Nullarbor to make multiple reports easier to manage.

**Comment by tseemann** [comment]
@kwongj I haven't noticed this bug occurring anymore. Have you?  Two years ago!
