### ISSUE TITLE
minimap2 dependency

### ISSUE THREAD

**Issue by delfair** [tseemann/nullarbor#231]
Hello Torsten,
Excellent software. I'm enjoying (and learning a lot) using nullarbor and your other programs.
I had a small issue with a dependency on minimap2 (https://github.com/lh3/minimap2). Without this the pipeline runs (with make -k option) but the report directory isn't created at the end. 
Easily fixed after examining the log file, but nullarbor.pl --check doesn't check for minimap2 so this might save someone some time...
Del

**Comment by tseemann** [comment]
Nullarbor does not depend on `minimap2` itself, but one of it's dependencies does: Snippy 4.x. It is assumed you have all the dependences working when you run `nullarbor.pl --check`.
 
What does `snippy --check` say?

I strongly recommend the use of bioconda or brew to install this complicated piece of software.
