### ISSUE TITLE
Running nullarbor.pl on assembled genomes

### ISSUE THREAD

**Issue by com31** [tseemann/nullarbor#243]
How can we run the nullarbor.pl with assembly option switched off? This may come handy when analysing already assembled genomes available in public databases.

**Comment by tseemann** [comment]
There is no way to do this in  Nuillarbor, sorry. 
It is planned however.

We do have a `--prefill` option which we use here, to re-use existing assemblies.
https://github.com/tseemann/nullarbor#prefilling-data
You still need reads however.

The underlying Snippy tool has a special wrapper called `snippy-multi` which allows PE reads and Contigs in it's input file. But it only does the phylo tree and nothing else.

https://github.com/tseemann/snippy#using-snippy-multi

Other options may be to see if Bohra supports what you desire:
https://github.com/kristyhoran/bohra
