### ISSUE TITLE
Nullarbor html report to a pdf file 

### ISSUE THREAD

**Issue by MostafaYA** [tseemann/nullarbor#246]
Hi Torsten, 
I was wondering if the nullarbor html report could be converted into a pdf file so that it could be used as a supplement for a publication, for example. 
Whether this could be possible within Nullarbor or if you forward me to a tool for doing that, this would be graet. 
Best regards,

**Comment by tseemann** [comment]
Options:
* In your web browser, select FILE -> PRINT -> SAVE AS PDF ?
* Submit to a journal that accepts HTML supplementary info
* Use `pandoc` or some other conversion tool

I won't be adding support within Nullarbor, as HTML -> PDF is hard due to page-breaks.
