### ISSUE TITLE
Making Txt file Tab for the run

### ISSUE THREAD

**Issue by foamy1881** [tseemann/nullarbor#248]
I'm new and a PhD student analyzing genomics data. i manage to setup nullarbor and it said passed (saying i deserve a medal). However upon testing it on a small sub sample set it return with an error message regarding the sample file name. If not mistaken the txt file to run nullabor2 is ID,R1,R2. It can't read sequence of R2. Can anyone please guide me? 

nullarbor.pl --name MtbNull2 --mlst saureus -ref ../../ReferenceGenome/NC000962.gbk --input null2mtb10.txt --outdir MtbNull2
[07:13:57] Hello yfong
[07:13:57] This is nullarbor.pl 2.0.20181010
[07:13:57] Send complaints to Torsten Seemann
[07:13:57] Scanning --ref for problematic sequence IDs...
[07:13:57] Using reference genome: /home/yfong/Documents/ReferenceGenome/NC000962.gbk
'07:13:57] ERROR: Isolate 'M001' - can not read sequence #2 of 1 files: '/home/yfong/Documents/SequenceFiles/M001_R2.fastq.gz

name from sample file txt

M001	/home/yfong/Documents/SequenceFiles/M001_R1.fastq.gz	/home/yfong/Documents/SequenceFiles/M001_R2.fastq.gz
M002	/home/yfong/Documents/SequenceFiles/M002_R1.fastq.gz	/home/yfong/Documents/SequenceFiles/M002_R2.fastq.gz
M003	/home/yfong/Documents/SequenceFiles/M003_R1.fastq.gz	/home/yfong/Documents/SequenceFiles/M003_R2.fastq.gz

**Comment by tseemann** [comment]
The format is `ID <tab> R1 <tab> R2`  (no spaces, must be a TAB character).

**Comment by foamy1881** [comment]
Yes i used the excel to create the txt output. You are right it is an issue with the TAB character and I fixed it as per suggestion using dos2unix. Is running now:) woohoo.. I'm testing on 10 samples before proceeding to 600+ isolates. Thanks!
