### ISSUE TITLE
ERROR: Could not find .aligned.fa/.vcf in samplename make: *** [Makefile:108: core.aln] Error 2

### ISSUE THREAD

**Issue by sharbie88** [tseemann/nullarbor#253]
I've been running Nullarbor for a while and working fine.  Left it for a couple of weeks and now not working - maybe something needs updating?, although I've run `conda update -n nullarbor_env --all`

`make preview` appeared to work ok from the index.html: file:///home/sharb/Documents/Nullarbor/8_ST22_testmakefile/report/index.html

when I ran the full program, however, no report file was created, all the .gff files remained and I got the .aligned.fa/.vcf and core.aln error 2 - see attached log file and makefile

[nullarbor.log](https://github.com/tseemann/nullarbor/files/3963025/nullarbor.log)
[Makefile.txt](https://github.com/tseemann/nullarbor/files/3963034/Makefile.txt)

Can you help please?

**Comment by andersgs** [comment]
Hi @sharbie88. From the logs it looks like you need to downgrade samtools from version 1.10 to 1.9. That is a known bug that is being fixed. 

You can try `conda install -c bioconda samtools=1.9`

Then, remove all the .gff files: 

`rm *.gff`

Then run `make`. 

Good luck.

**Comment by andersgs** [comment]
It seems there is also some confusion around kraken. It is running kraken 1 but it is calling a `classify` executable from Kraken 2! @tseemann this is truly bizarre!

```/home/sharb/miniconda3/envs/nullarbor_env/bin/../plugins/taxoner/kraken.sh
/home/sharb/miniconda3/envs/nullarbor_env/libexec/classify: invalid option -- 'd'
Usage: classify [options] <fasta/fastq file(s)>

Options: (*mandatory)
* -H filename      Kraken 2 index filename
* -t filename      Kraken 2 taxonomy filename
* -o filename      Kraken 2 options filename ```

@sharbie88 can you paste the output of `conda list` while in the active env? Thank you.

**Comment by sharbie88** [comment]
@andersgs here's the 'conda list' from inside nullarbor_env.

[condalista.txt](https://github.com/tseemann/nullarbor/files/3963673/condalista.txt)

running a small batch now.  I'll let you know how it goes.  Thanks.

**Comment by tseemann** [comment]
```
ead1="PC0051a-S0051/R1.fq.gz" read2="PC0051a-S0051/R2.fq.gz" outfile="PC0051a-S0051/kraken.tab" cpus=4 opts="" /home/sharb/miniconda3/envs/nullarbor_env/bin/../plugins/taxoner/kraken.sh
/home/sharb/miniconda3/envs/nullarbor_env/libexec/classify: invalid option -- 'd'
Usage: classify [options] <fasta/fastq file(s)>
```

This is an old problem with conda recipes for kraken1 and kraken2 clashing and breaking each other.  

The only way people have resolved it is to install the latest miniconda3 from scratch... It's not a nullarbor issue specifically.

**Comment by sharbie88** [comment]
@tseemann 'from scratch' - do you mean `rm miniconda3` and then reinstall the latest miniconda3 from the website?  and all of the dependencies, e.g. Nullarbor, will still be ok?

**Comment by sharbie88** [comment]
although the small batch worked, another batch doesn't work with same error as above - it stops after mlst with the following error (attached is makefile and .log):
```
Creating TSV file: core.txt
Running: snp-sites -c -o core.aln core.full.aln
Warning: No SNPs were detected so there is nothing to output.
ERROR: Could not run: snp-sites -c -o core.aln core.full.aln
make: *** [Makefile:108: core.aln] Error 2
make: *** Waiting for unfinished jobs....

```

[nullarbor_tomlst.log](https://github.com/tseemann/nullarbor/files/3973150/nullarbor_tomlst.log)
[Makefile.txt](https://github.com/tseemann/nullarbor/files/3973200/Makefile.txt)

I'm trying the small batch samples with the larger batch .fasta file.

**Comment by tseemann** [comment]
Yes. Assuming it's in the standard place:

```
rm -fr ~/miniconda3
rm -fr ~/.conda
rm -f ~/.condarc
```
Then follow all these exactly:
https://bioconda.github.io/user/install.html

Then
```
conda create -n nullarbor_env nullarbor
conda activate nullarbor_env
nullarbor.pl --check
```
