### ISSUE TITLE
Kraken quibble

### ISSUE THREAD

**Issue by biobrad** [tseemann/nullarbor#256]
When extracting this => minikraken_2017101**9**_4GB.tgz  

It creates a folder called this => minikraken_2017101**3**_4GB  <<<<<< folder has one number different from what Nullarbor check looks for.

Then when you run the Nullarbor check, it does this:
[08:06:49] ERROR: Can not find file /home/biobrad/minikraken_20171019_4GB/database.idx required by kraken.

Work around is to obviously change the folder name to the correct name.

**Comment by tseemann** [comment]
@biobrad hmmm - you are right, how annoying!
it seems they got the date wrong on the 4GB one but the 8GB is correct:

```
minikraken_20171013_4GB
minikraken_20171019_8GB
minikraken_20171101_4GB_dustmasked
minikraken_20171101_8GB_dustmasked
```

I will fix the docs.
