### ISSUE TITLE
Final report not generated and need help understanding make preview

### ISSUE THREAD

**Issue by ramay** [tseemann/nullarbor#257]
Hi ,
I have run nullarbor on 24 Ecoli. The report failed to generate because it couldn't find the core.txt. Reading through other comments. I found out that I should run make preview to quickly look at the tree and quality of these samples. While the quality is good, the tree doesn't look that great. 

The 10 samples labeled ECOLI 1-10 are obtained from the reference laboratory and we expect the other samples to be similar to them phylogenomically. My main interest is in virulence factors and AMR profiles of these samples but I thought it would be good to gather other information also. I can see that the information I need is in the resistome and virulome files but I would like to understand what is wrong that the report is not generating. Is there a way to not generate the core genome as these samples are different?

Thanks!
Hena

<img width="1370" alt="Screen Shot 2020-02-12 at 10 18 56 AM" src="https://user-images.githubusercontent.com/4459835/74360302-0862c780-4d82-11ea-8d91-0665d8cfb7eb.png">

**Comment by mabouelk** [comment]
I hope you can find somebody to help you.

**Comment by tseemann** [comment]
@ramay thank you for using `make preview` first, that was a good idea.
The preview report also should have another two tables with a distance matrix and a FASTQ/read summary.   Look at the `DEPTH` column?  What reference did you use?

**Comment by ramay** [comment]
I did look at the depth and they seem fine. 
Isolate | Reads | Yield | GeeCee | MinLen | AvgLen | MaxLen | AvgQual | Depth | Quality
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
21B | 3231886 | 477952597 | 50.5 | 60 | 147 | 151 | 32.7 | 101 | &#10004;
21A | 3921148 | 579998179 | 50.5 | 60 | 147 | 151 | 32.6 | 122 | &#10004;
E_coli6 | 3348572 | 495105393 | 50.1 | 60 | 147 | 151 | 32.7 | 104 | &#10004;
E_coli10 | 2701702 | 399396912 | 50.9 | 60 | 147 | 151 | 31.8 | 84 | &#10004;
19A | 2806318 | 414318036 | 50.7 | 60 | 147 | 151 | 32.6 | 87 | &#10004;
143B | 2599372 | 384314389 | 50.3 | 60 | 147 | 151 | 32.5 | 81 | &#10004;
E_coli9 | 2923732 | 432150061 | 50.4 | 60 | 147 | 151 | 32.5 | 91 | &#10004;
E_coli4 | 2555190 | 377968098 | 50 | 60 | 147 | 151 | 32.6 | 80 | &#10004;
E_coli5 | 3460908 | 511519640 | 50 | 60 | 147 | 151 | 32.7 | 108 | &#10004;
E_coli1 | 5619244 | 831699179 | 50.2 | 60 | 148 | 151 | 32.7 | 176 | &#10004;
46B | 2703996 | 399618787 | 50.3 | 60 | 147 | 151 | 32.6 | 84 | &#10004;
77C | 2535900 | 374782318 | 50 | 60 | 147 | 151 | 32.6 | 79 | &#10004;
E_coli2 | 3658140 | 541010590 | 50.2 | 60 | 147 | 151 | 32.5 | 114 | &#10004;
20B | 4209336 | 622560384 | 49.8 | 60 | 147 | 151 | 32.7 | 131 | &#10004;
111A | 3184898 | 470707333 | 50.2 | 60 | 147 | 151 | 32.6 | 99 | &#10004;
E_coli8 | 3200114 | 471797184 | 50 | 60 | 147 | 151 | 32.7 | 99 | &#10004;
E_coli3 | 2890250 | 427277427 | 50.2 | 60 | 147 | 151 | 32.7 | 90 | &#10004;
115C | 3325746 | 490246319 | 50.3 | 60 | 147 | 151 | 32.6 | 103 | &#10004;
E_coli7 | 3883120 | 574054141 | 50.4 | 60 | 147 | 151 | 32.7 | 121 | &#10004;
55B | 2554378 | 377792183 | 50.3 | 60 | 147 | 151 | 32.6 | 80 | &#10004;
20A | 2792552 | 412709687 | 49.8 | 60 | 147 | 151 | 32.7 | 87 | &#10004;
111B | 3674318 | 542280777 | 50.2 | 60 | 147 | 151 | 32.6 | 114 | &#10004;
69C | 2581400 | 381530619 | 50.3 | 60 | 147 | 151 | 32.5 | 80 | &#10004;
55C | 2621506 | 387354166 | 50.3 | 60 | 147 | 151 | 32.6 | 82 | &#10004;

**Comment by ramay** [comment]
The reference used was used was ECOLI_GCF_000005845.2_ASM584v2_genomic.gbff. 
Thanks!
Hena

**Comment by tseemann** [comment]
Your sequencing stats look ok.
If you already ran a full nullarbor, you can look at `denovo.tab` to assess the assemblies too.
Does that exist?

**Comment by ramay** [comment]
I managed to generate the report ! The problem was with snippy and samtool version conflict. I downloaded the lastest version of snippy(4.5) after reading about it in snippy issues.
Thanks for all your help!
Hena

**Comment by tseemann** [comment]
@ramay glad to hear!   thanks for letting me know.

**Comment by dan-hud** [comment]
I was also having this issue, server was running snippy 4.4.5, updating to the latest release (4.6) solved the issue.

**Comment by tseemann** [comment]
Thank you @dan-hud for letting us know, appreciated.
