### ISSUE TITLE
Makefile:133 issue

### ISSUE THREAD

**Issue by peflanag** [tseemann/nullarbor#258]
Hi All,

I had nullarbor working in Ubuntu OS in Parallels Desktop on macOS. It ran fine with a few saureus samples and then I tried with some mycobacteria samples and was running for a while till I got the following error. Not sure what it means since it ran ok with saureus. I pasted the end of my shell below.

The fastq files are located on the macOS vol that the input file points to in the ubuntu shell. 
The outdir is written to the ubuntu desktop since it cant seem to write to macOS volume.
make ref.fa preview ran fine first and then I ran

make again
make

Any help would be great.

Cheers,

P

Connectors: 8 Extenders: 206
Connections and extensions in  0.347620s wall, 1.300000s user + 0.010000s system = 1.310000s CPU (376.8%)
Contigs out: 208 Genome: 4324430 N50: 54005 L50: 26
Assembled in  0.827751s wall, 3.120000s user + 0.010000s system = 3.130000s CPU (378.1%)

DONE
read1="12IE02/R1.fq.gz" read2="12IE02/R2.fq.gz" outdir="12IE02" cpus=4 opts="" /home/peter/miniconda3/bin/../plugins/assembler/skesa.sh
skesa --fastq 12IE02/R1.fq.gz,12IE02/R2.fq.gz --cores 4 --vector_percent 1.0 --contigs_out 12IE02/contigs.fa 

Error opening 12IE02/R1.fq.gz
make: *** [Makefile:133: 12IE02/contigs.fa] Error 1
(base) peter@ubuntu:~/Desktop/TB_Nullarbor_Test$

**Comment by tseemann** [comment]
It is unclear how sharing a Macos filesystem to a Linux host in Parallels will work. It may not provide a POSIX Unix compliant file system. 

The error is running the skesa command for the 12IE02 isolate.

You should go into the folder and try and run that command 12IE02manually:
```
cd ~/Desktop/TB_Nullarbor_Test
ls -lsa 12IE02
skesa --fastq 12IE02/R1.fq.gz,12IE02/R2.fq.gz --cores 4 --vector_percent 1.0 --contigs_out 12IE02/contigs.fa
```

**Comment by peflanag** [comment]
Cheers I got it to work on this sample!

**Comment by mabouelk** [comment]
@peflanag I am glad that works for you. Can you help me to replicate what you did? with link to download parellel and unbutu. I know that there are a lot of them out there but I wanna avoid any errors.

**Comment by peflanag** [comment]
Parellel Desktop was provided to my by work and I just Googled for a ubuntu download. but the version is Ububtu 18.04.4 LTS if that helps

**Comment by tseemann** [comment]
You can use VirtualBox for free instead: https://www.virtualbox.org/wiki/Downloads
Select "Mac OS X Hosts"

**Comment by mabouelk** [comment]
Yes I did last week as the Parallel is expensive and give me a trial for 14 days.



________________________________
