### ISSUE TITLE
make again - can't find pipeline instruction file/s

### ISSUE THREAD

**Issue by sharbie88** [tseemann/nullarbor#260]
I've had to remove an isolate from an existing run.  I've #-marked the isolate to remove it from the list of samples and run a make preview which was all good.   `make again` gave me the pipeline instruction `nice make all -j 2 -l 4 -C 402_NZAK3_191114 2>&1 | tee -a 402_NZAK3_191114/nullarbor.log` which I ran, but I get the message:
```
nice make all -j 2 -l 4 -C 402_NZAK3_191114 2>&1 | tee -a 402_NZAK3_191114/nullarbor.log
tee: 402_NZAK3_191114/nullarbor.log: No such file or directory
make: *** 402_NZAK3_191114: No such file or directory.  Stop.

```

I've attached the makefile and .log file if that helps.
[Makefile.txt](https://github.com/tseemann/nullarbor/files/4290554/Makefile.txt)
[nullarbor.zip](https://github.com/tseemann/nullarbor/files/4290556/nullarbor.zip)

**Comment by tseemann** [comment]
You need to go back to the main nullarbor folder first.
```
make again
cd ..
nice make all -j 2 -l 4 -C 402_NZAK3_191114 2>&1 | tee -a 402_NZAK3_191114/nullarbor.log
```
