### ISSUE TITLE
Error: can not read sequence

### ISSUE THREAD

**Issue by mdiricks** [tseemann/nullarbor#269]

**Comment by tseemann** [comment]
WSL/Unix doesn't understand `C:\` 
I think the input.tab will need to refer to the `/mnt/c/Users/diric/` folder.
Did you put TAB characters between the columns? 
Spaces will not work.

**Comment by mdiricks** [comment]
I automated the samples.tab file generation and now I don´t get this error anymore.
However, I have troubles with installing the databases for kraken2 and centrifuge (the wget command indicates etas of over 1000d...). I had no problems with installing the kraken database. Are the kraken2 and centrigue databases required? And if yes, any idea what the problem can be with the other two?
