### ISSUE TITLE
Can not read the 2nd files

### ISSUE THREAD

**Issue by buihoangphuc412** [tseemann/nullarbor#273]
I ran the nullabor by this code
nullarbor.pl --name Helicobacter --mlst Helicobacter_pylori --ref Comparative\ assembly/26695.fasta --input Strains.tab --outdir Nullabor/Output
But they informed me that the 2nd read files can not be read 
[01:19:34] Hello manager
[01:19:34] This is nullarbor.pl 2.0.20191007
[01:19:34] Send complaints to Torsten Seemann
[01:19:34] Scanning --ref for problematic sequence IDs...
[01:19:34] Using reference genome: /media/sf_Biolinux/Comparative assembly/26695.fasta
'01:19:34] ERROR: Isolate 'CKIN59' - can not read sequence #2 of 1 files: '/media/sf_Biolinux/Nullabor/Paired/C-KIN59_S11_L001_R2_001.fastq.gz
I checked carefully the tab files is correct, so I attached.
Could you 
[Strains.txt](https://github.com/tseemann/nullarbor/files/4935245/Strains.txt)

**Comment by tseemann** [comment]
Your input file is not in Unix text format.
It seems to have been created in Windows/DOS fromat.

RUn "dfos2unix" on it.

Or remove the ^M / \r line endings
