### ISSUE TITLE
ERROR: Could not run: snp-sites -c -o core.aln core.full.aln make: *** [Makefile:108: core.aln] Error 2

### ISSUE THREAD

**Issue by emv6** [tseemann/nullarbor#287]
Hi, 

I am running Nullarbor on a Singularity based container system and I have run this numerous times using make preview and eliminated any possible contaminants. I have also used seqtk sample to subsample the reads to a read depth of below 200. I am getting all the necessary individual folders with a separate .gff file per isolate, a core.full.aln, a core.ref.fa, a core.tab, core.txt, core.vcf, denovo.tab, input.tab, isolates.txt, makefile, mlst.tab, nullarbor.log, ref,fa, ref.fa.fai, resistome.tab and virulome.tab. I have changed the genome to see if this make a difference but i still get the same error. I am running Nullarbor V2. I was just wondering is there a way to bypass Snippy to then get a roary output and generate the report file. I have tried using make -k which allows me to run roary but i still get no individual or a combined report generated. It would be great to try and get a report generated to see the MlST, Virulome, Resistome and Roary data all in one report file any assistance that can be given will be most appreciated.

**Comment by emv6** [comment]
The issue has fixed now

**Comment by naikd0** [comment]
Hello emv6,

I am running into the same problem you did, I ran make, make all and make publish all giving me the same error with snp-sites. I ran the make -j which also gave me the roary file but no report generated. Could you tell me what you did to get the snp-sites working? I would really appreciate any help given.

naikd0

**Comment by emv6** [comment]
Hi naikdo, 

I ended up changing my reference genome as this was an issue with snippy as the reference genome i used from NCBI differed to much from my isolates. I also stopped using nullarbor on a singularity container and just used it in a conda environment. Just make sure all your isolates look the same and you don't have any contaminated isolates. 

I am not sure exactly what allowed snippy to work whether it was my change in reference genome or not running nullarbor on a container based environment. 

Sorry I can't be more help, 

Thanks, 
emv6

**Comment by naikd0** [comment]
emv6,

I understand, thank you for getting back to me. I have been using nullarbor on conda enviroment so that should not be the issue. If you did not use a ref from NCBI where did you find another if I may ask?

Thanks,
naikd0

**Comment by emv6** [comment]
Hi naikdo, 

Sorry about my late reply. I created my own reference genome using nanopore sequence and illumina sequence so a hybrid genome. I have recently however tried another genome from NCBI and the program seems to be working so that's great. 

Sorry I can't be more help. Hope you can figure out the answer. 

The other thing you could try is subsetting your reads using seqtk that could help?

Thanks, 

emv6
