### ISSUE TITLE
Resistome report

### ISSUE THREAD

**Issue by kwongj** [tseemann/nullarbor#30]
Do ticks represent 100% identity AND full length match?

**Comment by tseemann** [comment]
It seems the answer is *no*.

According to the code the green tick actually only looks at COVERAGE=100 where it is defined as below:

```
COVERAGE     100 * ($hit{length}-$hit{gaps}) / $hit{slen}),
IDENTITY         $hit{pident},
```

**Comment by tseemann** [comment]
Should we change this behaviour?

**Comment by tseemann** [comment]
It seems ticks are ONE HIT, with >95% COV. (no ID limit)
Orange ? is everything else
except no hits which is red cross.

```
        $hit = @hits == 1 && int($hits[0]->{'%COVERAGE'}) >= 95
             ? $self->pass_fail( +1 )
             : $self->pass_fail( 0, join(' + ', map { int($_->{'%COVERAGE'}).'%' } @hits) );
```

Should this be changed?

**Comment by tseemann** [comment]
I've now added a legend to help clarify:

![image](https://user-images.githubusercontent.com/453972/45263623-11a28300-b470-11e8-85ee-2b4b37c6d2e6.png)
