### ISSUE TITLE
MLST gives incorrect alleles and ST if --scheme is specified

### ISSUE THREAD

**Issue by kwongj** [tseemann/nullarbor#37]

**Comment by tseemann** [comment]
1. I need an example
2. is this is a mlst bug not nullarbor?

**Comment by kwongj** [comment]
1. https://bioinformatics.mdu.unimelb.edu.au/~STUDENT%5cjkwong1/nullarbor/KPC.20151112.st258/index.html

2. Yes, I think MLST bug, not nullarbor

**Comment by tseemann** [comment]
I think this is solved now with new MLST.
