### ISSUE TITLE
assembly error using --accurate results in duplicate contig

### ISSUE THREAD

**Issue by kwongj** [tseemann/nullarbor#41]
When running _nullarbor_ using `--accurate`, assembly occasionally results in a duplicate contig:
<img width="498" alt="duplicate-contig" src="https://cloud.githubusercontent.com/assets/7855976/12748607/7a366552-c9ff-11e5-9f2d-1d0ea7a4a612.png">

Running _spades.py_ manually, using the same settings `--careful --only-assembler --cov-cutoff auto` produces the same duplication in the resulting `scaffolds.fasta` file, but not in the `contigs.fasta` file.

This only occurred in 1 out of 22 sequencing QC runs for the _Listeria monocytogenes_ strain EGD-e. No idea why it didn't occur in the others.

**Comment by tseemann** [comment]
This is a rare occuring bug in Spades 3.5 to 3.6.2 where contigs are *sometimes* not removed from the assembly during scaffolding.

We are hoping 3.7.0 will resolve this!
