### ISSUE TITLE
snippy error

### ISSUE THREAD

**Issue by bforde** [tseemann/nullarbor#42]
Hi Torsten,

The latest brew recipe for nullarbor throws an error when running snippy. I blieve this was previously flagged and fixed (https://github.com/tseemann/snippy/issues/45)

Changes to the snippy code (https://github.com/tseemann/snippy/commit/a8dc9b2b98a3a556c02c55eb628ea1656bc5a34d) are not present in the version of snippy (v2.9) packaged with the nullarbor brew recipe.

Changing the code results in an error with freebayes-parallel

`### freebayes-parallel reference/ref.txt 4 -p 1 -q 20 -m 60 --min-coverage 10 -V -f reference/ref.fa snps.bam > snps.raw.vcf

parallel: Error: --tollef has been retired.
parallel: Error: Remove --tollef or use --gnu to override --tollef.
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
/home/smrtanalysis/.linuxbrew/bin/freebayes-parallel: line 40: 22492 Exit 255                ( cat $regionsfile | parallel -k -j $ncpus "$command --region {}" )
     22493 Done                    | vcffirstheader
     22495 Aborted                 (core dumped) | vcfstreamsort -w 1000
     22497 Aborted                 (core dumped) | vcfuniq
`

**Comment by tseemann** [comment]
I'm working on fixing all this up.   

In the meantime, you can try this!

```
brew upgrade snippy --HEAD
brew upgrade nullarbor --HEAD
brew install trimmomatic
```

**Comment by bforde** [comment]
Thanks.

I just added the --gnu flag to freebayes-parallel script and everything ran fine.

in freebayes/bin/freebayes-parallel

change
parallel -k -j $ncpus "$command --region {}
to 
parallel --gnu -k -j $ncpus "$command --region {}

**Comment by tseemann** [comment]
Oh that's an old problem with a legacy `/etc/parallel.conf` (or similar) file you have leftover?

**Comment by bforde** [comment]
Yeah possibly.
It does explain a few things.
I have fixed it at login so should no longer be an issue

**Comment by lutaoact** [comment]
I use `parallel` on centos 6 and meet the same error. Remove `--tollef` from `/etc/parallel/config`, then everything works well.

**Comment by tseemann** [comment]
It's amazing how often this `parallel` bug comes back!
