### ISSUE TITLE
can't install blast for nullarbor

### ISSUE THREAD

**Issue by pyhuang1** [tseemann/nullarbor#47]
linuxmint@linuxmint ~/nullarbor $ brew install nullarbor
==> Installing nullarbor from tseemann/bioinformatics-linux
==> Installing dependencies for tseemann/bioinformatics-linux/nullarbor: blast, bedtools, cd-hit, mcl, mafft, libxml2, gettext, lib
==> Installing tseemann/bioinformatics-linux/nullarbor dependency: blast
==> Downloading ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.31/ncbi-blast-2.2.31+-src.tar.gz
Already downloaded: /home/linuxmint/.cache/Homebrew/blast-2.2.31.tar.gz
==> Patching
patching file c++/include/corelib/ncbimtx.inl
==> ./configure --prefix=/home/linuxmint/.linuxbrew/Cellar/blast/2.2.31_1 --libdir=/home/linuxmint/.linuxbrew/Cellar/blast/2.2.31_1/libexe
==> make
Last 15 lines from /home/linuxmint/.cache/Homebrew/Logs/blast/02.make:
                                        ^
compilation terminated.
make[3]: *** [test_boost.o] Error 1
make[3]: Leaving directory `/tmp/blast20160303-61606-9bhsht/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
FAILED: src/corelib/Makefile.test_boost.lib
make[3]: Entering directory `/tmp/blast20160303-61606-9bhsht/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
/bin/rm -f libtest_boost.a .test_boost.dep .libtest_boost.a.stamp
/bin/rm -f /tmp/blast20160303-61606-9bhsht/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libtest_boost.a /tmp/blast20160303-61606-9bhsht/ncbi-blast-2.2.31+-src/c++/ReleaseMT/status/.test_boost.dep \
	    /tmp/blast20160303-61606-9bhsht/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libtest_boost-static.a /tmp/blast20160303-61606-9bhsht/ncbi-blast-2.2.31+-src/c++/ReleaseMT/status/.test_boost-static.dep
make[3]: Leaving directory `/tmp/blast20160303-61606-9bhsht/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
make[2]: *** [all.nonusr] Error 2
make[2]: Leaving directory `/tmp/blast20160303-61606-9bhsht/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
make[1]: *** [all_r.real] Error 5
make[1]: Leaving directory `/tmp/blast20160303-61606-9bhsht/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build'
make: *** [all] Error 2

READ THIS: https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-science/issues

**Comment by ahmedmagds** [comment]
same problem

**Comment by tseemann** [comment]
@ahmedmagds @pyhuang1 This is a problem with the BLAST formula in Brew. 

Try `brew install blast --without-check --without-static`
