### ISSUE TITLE
nullabor install breaks

### ISSUE THREAD

**Issue by smichnowicz** [tseemann/nullarbor#48]
Dear Group
This issue appears to be very similar to issue #47 
I am trying to install nullabor on a Ubuntu 14.04 machine.
The "brew install nullarbor" command produces compile errors. Examining ~/.cache/Homebrew/Logs/blast/02.make it appears that the Boost headers can not be found. The gcc command does not seem to list the locations (-I)  They are installed in the system (/usr/include/boost) as well as within linuxbrew (e.g.  brew install boost
Warning: boost-1.60.0_1 already installed
)
Is there a way to include extra compile paths (i.e. -I<path>) into the brew command?

regards
Simon

**Comment by dmaccannell** [comment]
+1 on this.  I was about to make a report.

**Comment by ahmedmagds** [comment]
same problem here

**Comment by smichnowicz** [comment]
I found out a way to install nullabor
brew install blast --without-check
brew install nullarbor

I'm not sure what effect "--without-check" does to blast but I am sure it works OK
regards
Simon

**Comment by tseemann** [comment]
@smichnowicz is right - the way to get around this is `brew install blast --without-check --without-static`
