### ISSUE TITLE
Installing Nullarbor on Bio-linux 8.0 (Ubuntu 14.10)

### ISSUE THREAD

**Issue by ramjet10** [tseemann/nullarbor#49]
I just installed Bio-linux and Nullarbor on a couple of my students laptops. The nullarbor installation had a few issues and the issues were the same on each computer (different specs). 
Here is what I did to get nullarbor installed on each machine, maybe this can help someone else.

Blast install fails.
>brew install blast --without-check
>brew install nullarbor

openssl install fails
>brew remove curl
>brew install curl
>brew install nullarbor

librsvg install fails
>sudo apt-get install libgtk-3-dev
>brew install librsvg
>brew install nullarbor

**Comment by ahmedmagds** [comment]
Still Blast is not installed though I used the above commands

**Comment by ramjet10** [comment]
Sorry I am a noob to all this myself - so can't really help unless I know more details.

**Comment by tseemann** [comment]
You had an extra 's" on your blast install command. Try `brew install blast --without-check --without-static`

**Comment by ramjet10** [comment]
Very sorry about the extra 's' ahmedmagds, hope it didn't hold you up too long.

I also a bit of trouble setting up cpan modules when actually running nullarbor on my system and also the MAXCONTIGLENGTH issue with prokka comes up as well because my strain names were too long, but eventually got everything to run fine on Ubuntu. I will run through the issues again on my students laptops and post what I did to get things running in case anyone finds it helpful.

**Comment by tseemann** [comment]
I also recommend
`brew upgrade prokka --HEAD` 
`brew upgrade snippy --HEAD`
etc
to get the latest versions of the tools I write.
