### ISSUE TITLE
error 1

### ISSUE THREAD

**Issue by ahmedmagds** [tseemann/nullarbor#51]
nice make -j 1 -C /media/sf_linuxpasty/data/ahmedtest4                        [10:10AM]
make: Entering directory `/media/sf_linuxpasty/data/ahmedtest4'
mkdir -p Isolate1
any2fasta.pl /media/sf_linuxpasty/data/Pm70.fna > ref.fa
samtools faidx ref.fa
fq --quiet --ref ref.fa /media/sf_linuxpasty/data/P1234_1.fastq.gz /media/sf_linuxpasty/data/P1234_2.fastq.gz > Isolate1/yield.dirty.tab
Calculating depth, using size 2295190
trimmomatic PE -threads 3  /media/sf_linuxpasty/data/P1234_1.fastq.gz /media/sf_linuxpasty/data/P1234_2.fastq.gz Isolate1/R1.fq.gz /dev/null Isolate1/R2.fq.gz /dev/null ILLUMINACLIP:/home/manager/.linuxbrew/Cellar/nullarbor/1.01/bin/../conf/trimmomatic.fa:1:30:11 LEADING:10 TRAILING:10 MINLEN:30
TrimmomaticPE: Started with arguments:
 -threads 3 /media/sf_linuxpasty/data/P1234_1.fastq.gz /media/sf_linuxpasty/data/P1234_2.fastq.gz Isolate1/R1.fq.gz /dev/null Isolate1/R2.fq.gz /dev/null ILLUMINACLIP:/home/manager/.linuxbrew/Cellar/nullarbor/1.01/bin/../conf/trimmomatic.fa:1:30:11 LEADING:10 TRAILING:10 MINLEN:30
Using PrefixPair: 'AGATGTGTATAAGAGACAG' and 'AGATGTGTATAAGAGACAG'
Using PrefixPair: 'TACACTCTTTCCCTACACGACGCTCTTCCGATCT' and 'GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'

Using Long Clipping Sequence: 'GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG'

Using Long Clipping Sequence: 'TTTTTTTTTTAATGATACGGCGACCACCGAGATCTACAC'

Using Long Clipping Sequence: 'TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG'

Using Long Clipping Sequence: 'TTTTTTTTTTCAAGCAGAAGACGGCATACGA'

Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTGACGCTGCCGACGA'

Using Long Clipping Sequence: 'AGATCGGAAGAGCTCGTATGCCGTCTTCTGCTTG'

Using Long Clipping Sequence: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'

Using Long Clipping Sequence: 'TACACTCTTTCCCTACACGACGCTCTTCCGATCT'

Using Long Clipping Sequence: 'GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'

Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA'

Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT'

Using Long Clipping Sequence: 'AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAG'

Skipping duplicate Clipping Sequence: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'

Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT'

Using Long Clipping Sequence: 'AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG'

Using Long Clipping Sequence: 
'CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT'

Skipping duplicate Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA'

Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC'

Using Long Clipping Sequence: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'

ILLUMINACLIP: Using 2 prefix pairs, 17 forward/reverse sequences, 0 forward only sequences, 0 reverse only sequences

Quality encoding detected as phred33

Input Read Pairs: 507695 Both Surviving: 507446 (99.95%) Forward Only Surviving: 138 (0.03%) 
Reverse Only Surviving: 96 (0.02%) Dropped: 15 (0.00%)

TrimmomaticPE: Completed successfully

fq --quiet --ref ref.fa Isolate1/R1.fq.gz Isolate1/R2.fq.gz > Isolate1/yield.clean.tab

Calculating depth, using size 2295190
kraken --threads 3 --preload --paired Isolate1/R1.fq.gz Isolate1/R2.fq.gz | kraken-report > Isolate1/kraken.tab

Loading database... complete.

507446 sequences (153.26 Mbp) processed in 23.622s (1288.9 Kseq/m, 389.28 Mbp/m).
  490768 sequences classified (96.71%)
  16678 sequences unclassified (3.29%)
rm -f -r Isolate1/megahit
mkdir -p Isolate1
megahit --min-count 3 --k-list 21,31,41,53,75,97,111,127 -t 3 --memory 0.5 -1 Isolate1/R1.fq.gz -2 Isolate1/R2.fq.gz --out-dir Isolate1/megahit --min-contig-len 500
7.0Gb memory in total.

Using: 3.852Gb.

MEGAHIT v1.0.3

--- [Wed Apr  6 10:15:46 2016] Start assembly. Number of CPU threads 3 ---

--- [Wed Apr  6 10:15:46 2016] k list: 21,31,41,53,75,97,111,127 ---

make: *** [Isolate1/contigs.fa] Error 1

make: Leaving directory `/media/sf_linuxpasty/data/ahmedtest4'

**Comment by tseemann** [comment]
Looks like `megahit` is failing.

What happens if you run it manually?

```
megahit --min-count 3 --k-list 21,31,41,53,75,97,111,127 -t 3 --memory 0.5 -1 Isolate1/R1.fq.gz -2 Isolate1/R2.fq.gz --out-dir Isolate1/megahit --min-contig-len 500
```

I suspect maybe you don't have enough RAM ?

**Comment by tseemann** [comment]
@ahmedmagds Any update on your megahit problem?

**Comment by ahmedmagds** [comment]
Sorry I was away for sometime but I kept trying and still Nothing new. May be I am doing something wrong with the files thats why megahit cant read it

manager@bl8vbox[Isolate1] megahit --min-count 3 --k-list 21,31,41,53,75,97,111,127 -t 3 --memory 0.2 -1 Isolate1/R1.fq.gz -2 Isolate1/R2.fq.gz --out-dir Isolate1/megahit --min-contig-len 500             [10:42PM]
10.0Gb memory in total.
Using: 2.123Gb.
megahit: Cannot find file Isolate1/R1.fq.gz
manager@bl8vbox[Isolate1] megahit --min-count 3 --k-list 21,31,41,53,75,97,111,127 -t 3 --memory 0.2 -1 R1.fq.gz -2 R2.fq.gz --out-dir Isolate1/megahit --min-contig-len 500                               [10:42PM]
10.0Gb memory in total.
Using: 2.123Gb.
Traceback (most recent call last):
  File "/home/manager/.linuxbrew/bin/megahit", line 1059, in <module>
    sys.exit(main())
  File "/home/manager/.linuxbrew/bin/megahit", line 993, in main
    make_out_dir()
  File "/home/manager/.linuxbrew/bin/megahit", line 169, in make_out_dir
    os.mkdir(opt.out_dir)
OSError: [Errno 2] No such file or directory: 'Isolate1/megahit/'
manager@bl8vbox[Isolate1] megahit --min-count 3 --k-list 21,31,41,53,75,97,111,127 -t 3 --memory 0.2 -1 R1.fq.gz -2 R2.fq.gz --out-dir megahit --min-contig-len 500                                        [10:43PM]
megahit: Output directory megahit/ already exists, please change the parameter -o to another value to avoid overwriting.
manager@bl8vbox[Isolate1] megahit --min-count 3 --k-list 21,31,41,53,75,97,111,127 -t 3 --memory 0.2 -1 R1.fq.gz -2 R2.fq.gz --out-dir megahit2 --min-contig-len 500                                       [10:43PM]
10.0Gb memory in total.
Using: 2.123Gb.
MEGAHIT v1.0.3
--- [Thu Jun  9 22:44:25 2016] Start assembly. Number of CPU threads 3 ---
--- [Thu Jun  9 22:44:25 2016] k list: 21,31,41,53,75,97,111,127 ---

**Comment by tseemann** [comment]
You need to restart from scratch I think with the latest Nullarbor. something wierd is going on.
