### ISSUE TITLE
Software versions not declared in report

### ISSUE THREAD

**Issue by andersgs** [tseemann/nullarbor#52]
Hi Torst.

The current reports do not report a version for FastTree, and both spades and trimmomatic are declared with version '?'.

A.

**Comment by tseemann** [comment]
Spades finally supports `--version` so I can add it now.

Trimmomatic doesn't, and either does FastTree. I wasn't yet prepared to write manual code to decode their versions, but it is needed and I will do it eventually.

Plenty of other tools aren't listed either, but they are less critical to results.

**Comment by tseemann** [comment]
Resolved by da1bf825e4551b4d6ce45982112ad065d104a33b
