### ISSUE TITLE
snpEff fails when .gbk reference has no annotations

### ISSUE THREAD

**Issue by tseemann** [tseemann/nullarbor#53]
eg. KPC-producing Klebsiella pneumoniae ST258 draft genome sequence

```
### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

java.lang.RuntimeException: Error reading file '/home/schultzm/jobs/mdu/CPE_ongoing/CPE_ongoing_140416_accurate/2012-16110/2012-16110/reference/./ref/genes.gff'
java.lang.RuntimeException: FATAL ERROR: Most Exons do not have sequences!
        Chromosome names missing in 'reference sequence' file:  , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,
        Chromosome names missing in 'genes' file             : 
```

**Comment by vscooper** [comment]
Perhaps to add to this bug, here's where we stand.

### samtools faidx reference/ref.fa

### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.07 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 1.78 seconds elapse.
[bwa_index] Update BWT... 0.04 sec
[bwa_index] Pack forward-only FASTA... 0.05 sec
[bwa_index] Construct SA from BWT and Occ... 0.77 sec
[main] Version: 0.7.13-r1126
[main] CMD: bwa index reference/ref.fa
[main] Real time: 3.299 sec; CPU: 2.706 sec

### mkdir reference/genomes && cp -f reference/ref.fa reference/genomes/ref.fa


### mkdir reference/ref && bgzip -c reference/ref.gff > reference/ref/genes.gff.gz


### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

WARNING: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.
java.lang.RuntimeException: Error reading file '/home/vclocal/zerbaxa/nullarbor/1034/1034/reference/./ref/genes.gff'
java.lang.RuntimeException: FATAL ERROR: Most Exons do not have sequences!
There might be differences in the chromosome names used in the genes file ('/home/vclocal/zerbaxa/nullarbor/1034/1034/reference/./ref/genes.gff')
and the chromosme names used in the 'reference sequence' file.
Please check that chromosome names in both files match.
	Chromosome names missing in 'reference sequence' file:	'6537648'
	Chromosome names missing in 'genes' file             :	'unknown'

. File '/home/vclocal/zerbaxa/nullarbor/1034/1034/reference/./ref/genes.gff' line 5967
	'6537648	snippy	CDS	6537049	6537456	.	-	0	db_xref=GI:116053720,GeneID:4384098;note=GO_function: tRNA binding [goid GO:0000049] [evidence ISM]%3B GO_function: ribonuclease P activity [goid GO:0004526] [evidence ISM]%3B GO_process: tRNA processing [goid GO:0008033] [evidence ISM]%3B ;product=ribonuclease P;product_name_confidence="";protein_id=YP_794047.1;translation=MVSRDFDRDKRLLTARQFSAVFDSPTGKVPGKHVLLLARENGLDHPRLGLVIGKKNVKLAVQRNRLKRLIRESFRHNQETLAGWDIVVIARKGLGELENPELHQQFGKLWKRLLRNRPRTESPADAPGVADGTHA'

	at ca.mcgill.mcb.pcingola.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:132)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdBuild.createSnpEffPredictor(SnpEffCmdBuild.java:115)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:304)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:883)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:128)

**Comment by tseemann** [comment]
@vscooper there is something weird going on here. can you test with just `snippy` instead of via nullarbor?   and post an error report there with the actual GBK file?

**Comment by TrinidadMartin** [comment]
Hello, I am getting the same problem with the chromosomes:
`java.lang.RuntimeException: Error reading file '/Users/tmartinc/work/RL/PhD/Database/TB50seqLausanne/SNPs/snpEff/snpEff_latest_core/snpEff/./data/TB50/genes.gff'
java.lang.RuntimeException: FATAL ERROR: Most Exons do not have sequences!
	Chromosome names missing in 'reference sequence' file:	, , , , , , , , , , , , , , , , , , , 
	Chromosome names missing in 'genes' file             :	'tb50_10_tpg|BK006943.2|''tb50_11_tpg|BK006944.2|''tb50_12_tpg|BK006945.2|''tb50_13_tpg|BK006946.2|''tb50_14_tpg|BK006947.3|''tb50_15_tpg|BK006948.2|''tb50_16_tpg|BK006949.2|''tb50_1_tpg|BK006935.2|''tb50_2_tpg|BK006936.2|''tb50_3_tpg|BK006937.2|''tb50_4_tpg|BK006938.2|''tb50_5_tpg|BK006939.2|''tb50_6_tpg|BK006940.2|''tb50_7_tpg|BK006941.2|''tb50_8_tpg|BK006934.2|''tb50_9_tpg|BK006942.2|''tb50_mito_ref|NC_001224|''tig00000033''tig00000132''tig00000133'
`
I have checked and I have the same names in my exonerate gff and the fasta file 

`snpEff tmartinc$ grep "^>" ./data/TB50/sequences.fa 
>tb50_4_tpg|BK006938.2|
>tb50_15_tpg|BK006948.2|
>tb50_7_tpg|BK006941.2|
>tb50_16_tpg|BK006949.2|
>tb50_13_tpg|BK006946.2|
>tb50_2_tpg|BK006936.2|
>tb50_14_tpg|BK006947.3|
>tb50_10_tpg|BK006943.2|
>tb50_12_tpg|BK006945.2|
>tb50_11_tpg|BK006944.2|
>tb50_5_tpg|BK006939.2|
>tb50_8_tpg|BK006934.2|
>tig00000033
>tb50_9_tpg|BK006942.2|
>tb50_3_tpg|BK006937.2|
>tb50_6_tpg|BK006940.2|
>tb50_1_tpg|BK006935.2|
>tig00000132
>tig00000133
>tb50_mito_ref|NC_001224|`

Any idea please??
Thanks!!
Trini

**Comment by tseemann** [comment]
> my exonerate gff and the fasta file

I don't know what an exonerate gff is.

1. what version of nullarbor are you using?  `run --version and --check`
2. attach your genbank file here (check it has DNA sequence at the end)

**Comment by TrinidadMartin** [comment]
Hello!!

Exonerate is giving gff3 format output.

1. For nullarbor I don't have installed and, as I understand, it is not supporting my PacBio data: "Nullarbor currently only supports Illumina paired-end sequencing data"

2. I don't have a genbank file, only a gff and fasta, but I should be able to create a database with that right??
Here you are my files ;)

Thanks a lot for the quick answer!
Trini

[gff_and_fasta.zip](https://github.com/tseemann/nullarbor/files/3732873/gff_and_fasta.zip)

**Comment by tseemann** [comment]
This issues page is for users of Nullarbor. 
Yes, I don't support  Pacbio data so I don't know how/why you are using Nullarbor?
I only support Genbank or FASTA reference files.
Feel free to use `snpEff` directly and create own database.
Sorry I can't help you further.

**Comment by TrinidadMartin** [comment]
Thanks!
