### ISSUE TITLE
cairo dependency preventing install

### ISSUE THREAD

**Issue by vscooper** [tseemann/nullarbor#56]
Can't seem to complete installation of nullarbor owing to the following error. I noted you've wrestled with this issue with linuxbrew. Help is welcome, thanks.
`==> Installing nullarbor from tseemann/bioinformatics-linux
==> Installing dependencies for tseemann/bioinformatics-linux/nullarbor: cairo, homebrew/dupes/ncurses, readline, sqlite, gdbm, python, homebrew/dupes/m4
==> Installing tseemann/bioinformatics-linux/nullarbor dependency: cairo
==> Downloading http://cairographics.org/releases/cairo-1.14.6.tar.xz
Already downloaded: /home/vclocal/.cache/Homebrew/cairo-1.14.6.tar.xz
==> ./configure --prefix=/home/vclocal/.linuxbrew/Cellar/cairo/1.14.6_1 --enable-gobject=yes --enable-svg=yes --enable-tee=yes --enable-xcb=yes --enable-xlib=ye
Last 15 lines from /home/vclocal/.cache/Homebrew/Logs/cairo/01.configure:
checking for X11/extensions/shmproto.h... yes
checking for X11/extensions/shmstr.h... yes
checking whether cairo's Xlib surface backend feature could be enabled... yes
checking for cairo's Xlib Xrender surface backend feature... 
checking for xlib_xrender... no
checking for X11/extensions/Xrender.h... yes
checking for XRenderCreateSolidFill... yes
checking for XRenderCreateLinearGradient... yes
checking for XRenderCreateRadialGradient... yes
checking for XRenderCreateConicalGradient... yes
checking whether cairo's Xlib Xrender surface backend feature could be enabled... yes
checking for cairo's XCB surface backend feature... 
checking for xcb... no
checking whether cairo's XCB surface backend feature could be enabled... no (requires xcb >= 1.6 xcb-render >= 1.6 http://xcb.freedesktop.org)
configure: error:  XCB surface backend feature could not be enabled
`

**Comment by vscooper** [comment]
Actually was able to get past this bug following instructions here:
https://github.com/Linuxbrew/linuxbrew/issues/842

```
brew install linuxbrew/xorg/xorg
brew install cairo --with-x11
```

**Comment by tseemann** [comment]
@vscooper Yes, linuxbrew is going through some major changes in the ecosystem right now. Glad you got it working!
