### ISSUE TITLE
Core genome table/section should report length of core alignment across all isolates

### ISSUE THREAD

**Issue by andersgs** [tseemann/nullarbor#63]
While it is good to have some idea of how much of individual isolates map to the reference, in regards to generating the core SNPs that is irrelevant. What we really need is an estimate of the intersection, how much of the genome is represented in the core alignment from which the core SNPs are generated.

In a way, I assume snippy already has the code for this, as it identifies the core variable sites, it just needs to keep a running tally of all (variable+monomorphic) core sites.

**Comment by tseemann** [comment]
I think the size of the entries in `core.full.aln` contains this information. I should be able to add it.

**Comment by tseemann** [comment]
It does this now.
