### ISSUE TITLE
Add --noclip option to skip trimmomatic

### ISSUE THREAD

**Issue by tseemann** [tseemann/nullarbor#65]
For modern NextSeq reads they come preclipped of adaptors.

**Comment by kwongj** [comment]
Would it be possible to auto-detect whether the reads are clipped or not? E.g. Scan first 10-100 reads and check for adapters?

Also how will this affect trimming of low quality sequence?

**Comment by tseemann** [comment]
Most (all?) of the tools we use are robust to some low quality bases so I'm not too worried.

**Comment by tseemann** [comment]
@kwongj It would be good if we could auto-detect whether clipping is needed or not. This would save many terabytes of disk files and also speed up the pipeline.

**Comment by kwongj** [comment]
@tseemann I forgot about this post! Could we add the Illumina adapters to the Kraken database? If there are no hits, we could skip Trimmomatic?

**Comment by tseemann** [comment]
Yes the next Kraken database should add adaptors into it using taxon 81077 for artificial sequences or similar:

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=81077&lvl=3&lin=f&keep=1&srchmode=1&unlock

**Comment by tseemann** [comment]
@kwongj I have now made NOT trimming the default. See b7bdf86af638a96582f138232db2e97e53a31ee1

 Use `--trim` to enable it again.

**Comment by mdiricks** [comment]
Does this mean there occurs no trimming at all? So also no quality trimming?

**Comment by tseemann** [comment]
@mdiricks use `--trim` if you want it.

**Comment by mdiricks** [comment]
@tseemann, in the - - help only illumina adaptor trimming is mentioned that's why I was not sure if quality trimming was maybe performed still by default
