### ISSUE TITLE
some minor suggestions

### ISSUE THREAD

**Issue by flashton2003** [tseemann/nullarbor#73]
Hey Torst,

Looks awesome. Just thought I would leave some feedback, definitely in the 'enhancement' category, but i don't think I can tag it myself?
1. Downloadable pan-genome. Would be great for the pan-genome (genes in fasta) and presence/absence matrix from Roary to be download-able.
2. in addition to the core.aln, would be good to have the position of the variants in the reference genome. and any annotation of the variants if you have it done by snippy?
3. Possible minor bug, for me, the hover over tool set on the pictures is a bit unaligned, see below.
   ![screen shot 2016-06-08 at 09 53 37](https://cloud.githubusercontent.com/assets/2613906/15888974/21695eb4-2d61-11e6-9d59-48069d2f65ee.png)

You probably had these on your todo list anyway, but just in case!

**Comment by tseemann** [comment]
Phil

1. the nullarbor folder itself has all the files you want in it, but yes they aren't downloadable. the g_p_a.csv file should be - so it can be passed to Phandango etc. I hope to add phandango integration.

2. that info is also in the 'core.*' files in the nullarbor folder - it's just snippy output. but should be documented.

3. Yes it's a plotly.js bug in Chrome - it works fine in Safari, Edge, Firefox!
