### ISSUE TITLE
snippy-core matrix SNP count  inconsistencies.

### ISSUE THREAD

**Issue by musta1234** [tseemann/nullarbor#85]
Hello @tseemann,
I ran nullarbor on five genomes M1-M5 and got the pairwise core-SNP table below. However, manually comparing snps.vcf files gave very different numbers for those genome pairs with high (>200k) SNP differences. For example, ./M5/M5/snps.vcf has  184053 variants which I suppose means there are 184053 differences when comparing  M5 vs Reference. Same applies to all the high count SNP numbers. 

How do we account for this difference? Does snippy-core give weight to multiple nucleotide variants or count unmapped bases, or is there something I am missing here?
Thanks

Mustapha
 
ID 	M1 	M2 	M3 	M4 	M5 	Reference
M1 	0 	2 	2 	233360 	233842 	11
M2 	2 	0 	2 	233358 	233840 	13
M3 	2 	2 	0 	233360 	233842 	13
M4 	233360 	233358 	233360 	0 	141361 	233371
M5 	233842 	233840 	233842 	141361 	0 	233851
Reference 	11 	13 	13 	233371 	233851 	0

**Comment by tseemann** [comment]
The tree is built from **core** SNPs only.  These are sites which have coverage/depth in *all* of the samples. Because you have 2 clades far apart, not all the SNPs are co-existing.
