### ISSUE TITLE
mlst scheme specification

### ISSUE THREAD

**Issue by schultzm** [tseemann/nullarbor#86]
If I specify no scheme on the command line and a scheme isn't auto-detected, nullarbor.pl will fail to generate the makefile.  So, if I trick nullarbor.pl and specify a dummy scheme (e.g., 'abaumannii' for species _Morganella morganii_), nullarbor.pl will generate the makefile.  On running the pipeline, a different auto-detect scheme will be used (e.g for _Morganella morgannii_, with abaumannii specified as a dummy scheme, 'vcholerae' has been implemented by autodetect).    It would be great if we could override autodetect (e.g. I want ecoli instead of ecoli2).

**Comment by andersgs** [comment]
Or skip MLST all together if no scheme is available.

**Comment by tseemann** [comment]
Fixed @schultzm !
