### ISSUE TITLE
I run the nullarbor.pl script but no final report is created.

### ISSUE THREAD

**Issue by jb2cool** [tseemann/nullarbor#87]
I've finally managed to install Nullarbor on Bio-Linux 8 with the help of Stephen's install script and if I run 'nullarbor.pl --check' then it all looks ok but if I run the makefile against the demo data that Stephen included with his script I don't seem to get any tree generated.

It runs through lots of steps but there is no public_html folder created and no report/index.html that I can find.

I also tried with 'make all -j 4' to try and force it but still no joy

**Comment by jb2cool** [comment]
also tried with 'make all -j 4' to try and force it but still no joy

**Comment by stephenturner** [comment]
Did you happen to run into the issue with prokka and contig IDs being too long? I.e., see the comment at Line 263 and the sed hack. 

https://gist.github.com/stephenturner/005d4e4e322b8cf5b991d1d357527859#file-nullarbor-install-ubuntu1404-sh-L263

**Comment by jb2cool** [comment]
I'm not running this on any of my data yet, just the test/demo data that your script downloads. I'll try and see if your hackjob gets me any further.

**Comment by jb2cool** [comment]
Yes indeed that did sort me out, thanks

**Comment by jb2cool** [comment]
Duplicate of https://github.com/tseemann/nullarbor/issues/81

**Comment by jb2cool** [comment]
Well I thought it was just the sed hackjob I needed but it's back to doing the same thing on a freshly built machine (Even though it's built with the same script).

I create the samples.tab
run the nullarbor.pl to create the makefile
'fix' the makefile with the sed hackjob
run the makefile

**Comment by kwongj** [comment]
Can you post the commands that you used and some of the output that you get?

**Comment by jb2cool** [comment]
cd genometrackr

nullarbor.pl --name nullarbor --mlst senterica --ref /opt/genomes/senteritidisp125109.fa --input samples.tab --outdir nullarbor --force

sed -i 's/locustag SRR[0-9]*/locustag x/g' nullarbor/Makefile

nice make -j 4 -C /home/jason/genometrackr/nullarbor

[Makefile.txt](https://github.com/tseemann/nullarbor/files/384121/Makefile.txt)

**Comment by kwongj** [comment]
If you re-run the Makefile again by either running:
```$ nice make -j 4 -C /home/jason/genometrackr/nullarbor```

or entering the nullarbor directory and running the Makefile from there:
```$ cd /home/jason/genometrackr/nullarbor
$ make```

Nullarbor should pick up from where it left off.

The 4 files you listed are generated at the start of Nullarbor. Are the folders empty?

**Comment by jb2cool** [comment]
Folders all have;
abricate.tab
contigs.fa
denovo.tab
kraken.tab
megahit.log
mlst.tab
mlst2.tab
prokka directory
R1.fq.gz
R2.fq.gz
SRR1207xxx directory (matches the higher level directory)
yield.clean.tab
yield.dirty.tab

Two of them (SRR1207483 and SRR1207515) are a bit shorter with only;
contigs.fa
kraken.tab
megahit.log
R1.fq.gz
R2.fq.gz
SRR1207xxx directory (matches the higher level directory)
yield.clean.tab
yield.dirty.tab

**Comment by jb2cool** [comment]
here is the output of the job (different name this time)
[output.txt](https://github.com/tseemann/nullarbor/files/384295/output.txt)

**Comment by jb2cool** [comment]
if i keep re-running the make as you suggest it seems to get a little further every time. I now have denovo.tab, mlst.tab and mlst2.tab in the top level folder as well as a roary directory.

The final error which i can't get past is;

make: Entering directory `/home/jason/genometrackr/nullarborzsh'
mkdir -p SRR1207440
mkdir -p SRR1207460
mkdir -p SRR1207461
mkdir -p SRR1207468
mkdir -p SRR1207483
mkdir -p SRR1207515
snippy-core SRR1207440/SRR1207440 SRR1207460/SRR1207460 SRR1207461/SRR1207461 SRR1207468/SRR1207468 SRR1207483/SRR1207483 SRR1207515/SRR1207515
"any" is not exported by the List::Util module
Can't continue after import errors at /home/jason/.linuxbrew/bin/snippy-core line 5.
BEGIN failed--compilation aborted at /home/jason/.linuxbrew/bin/snippy-core line 5.
make: *** [core.aln] Error 255
make: Leaving directory `/home/jason/genometrackr/nullarborzsh'

**Comment by jb2cool** [comment]
Perhaps List::Util was missing, this seemed to fix it for me;
sudo cpan -f -i List::Util

**Comment by kwongj** [comment]
Yep - is it working now?

**Comment by jb2cool** [comment]
Yes, after adding List::Util this seems ok now.

**Comment by Myebenn** [comment]
Hi there,
I am experiencing a similar issue with Nullarbor going to completion but failing to generate a final html report (although all individual reports are created within the report folder). The error message I'm getting reads something like this:

[21:42:02] Hello ubuntu
[21:42:02] This is nullarbor-report.pl 1.25
[21:42:02] Send complaints to Torsten Seemann <torsten.seemann@gmail.com>
[21:42:02] Folder --outdir /home/ubuntu/efn/seqrun_3_repeat.3/merged.reads18Nov18/nhp.nullarbor.run18Nov18/report already exists.
[21:42:02] Identified 72 isolates.
[21:42:02] Generating: jobinfo
[21:42:02] Generating: seqdata
[21:42:02] Generating: identification
[21:42:02] Generating: mlst
[21:42:02] Generating: serotype
[21:42:02] WARNING: no analysis available for serotype
[21:42:02] Generating: resistome
[21:42:02] Generating: virulome
[21:42:03] Generating: assembly
[21:42:03] Generating: reference
[21:42:03] Generating: core
[21:42:03] Generating: snptree
[21:42:03] Generating: snpdist
[21:42:03] Generating: snpdensity
[21:42:03] Can't open /home/ubuntu/efn/seqrun_3_repeat.3/merged.reads18Nov18/nhp.nullarbor.run18Nov18/core.nway.tab in Nullarbor::Tabular::load
Makefile:48: recipe for target 'report/index.html' failed
make: *** [report/index.html] Error 1
make: Leaving directory '/home/ubuntu/efn/seqrun_3_repeat.3/merged.reads18Nov18/nhp.nullarbor.run18Nov18'

Grateful for your kind assistance in resolving this.

Cheers,
Ebenn

**Comment by sharbie88** [comment]
I am getting this error too.  What was the solution?

**Comment by myebenn** [comment]
Hi @sharbie88 
The problem didn't go away for me, however, @tseemann suggested that installing the newer version of Nullarbor should solve the issue. I was/am using nullarbor.pl 1.30-dev, whereas the current version is a Nullarbor 2.x. 
You could try to install the latest version and give it a go.

cheers

**Comment by tseemann** [comment]
@myebenn nullarbor 1.x uses snippy 3.x which will give you wrong answers. please ugprade if you can!

**Comment by myebenn** [comment]
👍 👍
I ended up running the individual programmes separately (spades, snippy, prokka, resfinder etc) with up to date versions since then hence did not upgrade, but will do so right away! Thx again @tseemann!

**Comment by peflanag** [comment]
Hi I am wondering can I reopen this issue? Maybe someone can help? @jb2cool @tseemann 

I ran the program on ubuntu in parrelles app on my iMac Pro. It ran first and seemed to work but notiuced there was not a report/index.html file there was only the attached image. 



I checked the versions and they all seemed fine and I tried what was mentioned in Snippy-Core Issue #51 running 

apt-get install liblist-moreutils-perl

The I ran nullarbor again but it failed with:


[14:57:23] Assigned 2576 locus_tags to CDS and RNA features.
[14:57:23] Writing outputs to /tmp/tmp.OFCkn5seeW/
[14:57:24] Generating annotation statistics file
[14:57:24] Generating Genbank and Sequin files
[14:57:24] Running: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.14.5 from https://github.com/tseemann/prokka' -Z \/tmp\/tmp\.OFCkn5seeW\/prokka\.err -i \/tmp\/tmp\.OFCkn5seeW\/prokka\.fsa 2> /dev/null
[14:57:27] Could not run command: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.14.5 from https://github.com/tseemann/prokka' -Z \/tmp\/tmp\.OFCkn5seeW\/prokka\.err -i \/tmp\/tmp\.OFCkn5seeW\/prokka\.fsa 2> /dev/null
make: *** [Makefile:130: E6206/contigs.gff] Error 2
make: Leaving directory '/media/psf/Home/IMRL_Sequencing/Tanya_MRSA/Nullarbor_Output'

I don't know what to do.
