### ISSUE TITLE
Pairwise core SNP distances and Core SNP density plots don't view well in chrome

### ISSUE THREAD

**Issue by aabarug** [tseemann/nullarbor#93]
Hi Torsten,

I recently installed Nullarbor 1.20 and ran a test dataset on it. When viewing the report, I noticed that the Pairwise core SNP distances and the Core SNP density plot doesn't deal well with being moused-over in Chrome (I've checked in Safari and Firefox - they are fine there). As this is a plotly plot, I think that's where the problem stems from. The mode-box that's meant to pop up on the top right of the plot instead expands to completely overlay the entire page. Or the icons are a jumbled mess to the right of the plot, not as large to cover the page but are enlarged a bit. I have some screenshots of what this looks like but will only share them directly upon request.

**Comment by tseemann** [comment]
@aabarug yes there is a bug/issue with CSS.  
I was provided a patch to fix this 5b7d74be03736aeffd1b6af4ce8e0b216a64bf8e
Let me know if it works for you.
