### ISSUE TITLE
No Report, Makefile exits with error 2

### ISSUE THREAD

**Issue by nate422** [tseemann/nullarbor#96]
I am running nullarborv 1.20 on 21 isolates.  The script executes, however, it can't seem to complete the snippy step.  This also seems to cut out roary, prokka, etc.  The snippy trackback is attached.  It appears as if not all isolate sets are having this problem.  Any idea, any help is appreciated!

[errors.txt](https://github.com/tseemann/nullarbor/files/647650/errors.txt)

**Comment by tseemann** [comment]
Can you try running it just with `make` instead of `make -j X` ?

Does snippy work alone?  Try `snippy --ref XXX --outdir /tmp/YYY --R1 WWW --R2 XXX`

Did you happen to create the .tab file on mac or windows or export from Excel?
