### ISSUE TITLE
Nullarbor Please report this to the chapmanb/cbl tap! Error: Cannot tap chapmanb/cbl: invalid syntax in tap!

### ISSUE THREAD

**Issue by darianokakpu** [tseemann/nullarbor#97]
Hello,

I am new to GitHub. The Nullarbor pipeline installation guide gave an error in the following command

brew tap chapmanb/cbl

/home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/qsignature.rb:7:in `<class:Qsignature>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/metal-gwas.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/metal-gwas.rb:7:in `<class:MetalGwas>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/scalpel.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/scalpel.rb:7:in `<class:Scalpel>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/libmaus.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/libmaus.rb:7:in `<class:Libmaus>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/rsem.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/rsem.rb:7:in `<class:Rsem>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/pindel.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/pindel.rb:7:in `<class:Pindel>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/caveman.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/caveman.rb:7:in `<class:Caveman>'
Please report this to the chapmanb/cbl tap!
Error: Invalid formula: /home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/cramtools.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/home/ubuntu/.linuxbrew/Library/Taps/chapmanb/homebrew-cbl/cramtools.rb:7:in `<class:Cramtools>'
Please report this to the chapmanb/cbl tap!
Error: Cannot tap chapmanb/cbl: invalid syntax in tap!
ubuntu@server-739c71d6-6d97-44c5-9236-2d6138188dee:~/Downloads$ 

Since it asks to be reported, I thought this is the best place to put it. 

Best,

Darian

**Comment by tseemann** [comment]
Darian,

That tap is not needed anymore. 
See https://github.com/tseemann/nullarbor#local-installation

Also, run `brew doctor` to check your setup is ok.

Torsten
